### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by lanjekarraj** [HoffmannTom/outlookbackupaddin#1]
I have 1.6.0 version installed.

And tried to run 1.7.0 installer. It prompted me to uninstall old version, and later 1.7.0 got installed.

Can upgrade (in place) be taken care in subsequent versions..

Thank you

**Comment by HoffmannTom** [comment]
Hello,
did you download the installer from the old homepage on codeplex or from github?
The release at https://github.com/HoffmannTom/outlookbackupaddin/releases should have the correct installer version 1.7.0.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
this feature is available in the development branch and will be part of the next release.
During uninstall, all settings will be preserved. Installation of new version will keep the settings therefore.

Greetings,
Thomas
