### ISSUE TITLE
hide OST file from the backup list

### ISSUE THREAD

**Issue by BigDie** [HoffmannTom/outlookbackupaddin#10]
Hello,
do you think should be possible to hide the .OST file from the list of Outlook file to backup?
I think there is no reason to backup that file and if you have a long list of PST archive could be hard to notice the .OST in the middle of the list. 
Maybe is possible to add an option like "Backup all PST file" alternative to "Backup all shown file" under the full list of file. Otherwise maybe is possible to add a registry key or an option in a configuration file to set the list of desired visible file extension.

Anyway thanks for your plug-in!

**Comment by HoffmannTom** [comment]
Hello,
actually the ost files should be already hidden. Currently files are hidden by checking the store type.
OST-Files usually have no file path within VSTO and have a special store type.
Thus they should currently be invisible (there is a registry key to enable ost store types).

Greetings,
Thomas

**Comment by BigDie** [comment]
In my case (Outlook 2013 on Windows 10) the .ost is displayed.
I installed the sw and I didn't make any change to the registy.
Can you point me to the registry key to disable ost store types? 

![2017-11-13 16_52_05-backup settings](https://user-images.githubusercontent.com/33317430/32734829-6bbb4300-c893-11e7-9c31-add7b3653596.png)

**Comment by HoffmannTom** [comment]
Hello,
could you please tell me which email provider and type (imap, pop, activeSync, ...) you are using
for the third account? Maybe I can investigate if further.
How to blacklist certain store types is dicussed here:
https://outlookbackupaddin.codeplex.com/discussions/640349
(HKCU\Software\CodePlex\BackupAddin\Settings --> RegSZ with name StoreTypeBlacklist)
The values are just coma separated numbers. The numbers are outlook internal numbers.
Maybe you have to experiment a bit to figure out the right value.
I could also send you a debug version of the add-in which would show the ID and further information for each data file / account.

Greetings,
Thomas

**Comment by BigDie** [comment]
the email provider is the company Exchange server.
Anyway setting the HKCU\Software\CodePlex\BackupAddin\Settings\StoreTypeBlacklist registry to 0 the OST file is now hided.
I wonder if there is a global setting (HKLM maybe) to set this to all users.

Thanks,
Andrea

**Comment by HoffmannTom** [comment]
Hello,
the storeType 0 means your primary Exchange mailbox according to
https://msdn.microsoft.com/en-us/library/microsoft.office.interop.outlook.olexchangestoretype(v=office.14).aspx
One option would be to use GPO to distribute the settings. A GPO template is within the zip package.

Another option would be to adjust the code (BackupUtils.cs).

Which exchange version are you using? I only tested with 2016.

Greetings,
Thomas

**Comment by Nusuthoid** [comment]
We have the same issue - OST file is being backed up, even if it is not enabled via GPO (setting is disabled). Because of that, I cannot mark "Backup all shown files", which means that users would have to select them manually (we have one PST archive per year) - which I want to avoid. Windows 10 machines, Outlook 2016, Exchange 2016. Is there a way to omit OST files?

**Comment by HoffmannTom** [comment]
Hello,
have you tried to set the registry key StoreTypeBlacklist as mentioned above?
You can disable the corresponding store type. 
The store types are documented in the link above. 
If this doesnt work, please send an export or screenshot of the registry entries.
Greetings, Thomas

**Comment by Nusuthoid** [comment]
Hello,

Here are the steps I have tried:
1. Set up the GPO [https://pasteboard.co/IeLSD1F.png](url)
2. GPO results [https://pasteboard.co/IeLSU4g.png](url)
3. However, the Backup Settings window didn't apply the changes (H:\MAIL was from my previous testing) [https://pasteboard.co/IeLTluP.png](url)
4. Changed registry key [https://pasteboard.co/IeLTuOT.png](url)
5. Backup Settings now doesn't show OST file, but GPO settings are not applied [https://pasteboard.co/IeLTNkr.png](url)

So, a couple of questions - can OST omitting be done without registry hack? And is there somewhere hidden Backup Settings that overrides GPO?

Kind regards, Ivan

**Comment by HoffmannTom** [comment]
Hello Ivan,
the configuration is done solely via registry. There is no "hacky" stuff anywhere.
GPOs are all about modifying the registry. Behind every GPO there is a set of registry settings.
GPOs are just a template or GUI for modfying the registry more easily.
So you dont need to configure the registry on client side manually, just use the GPO for this blacklist setting (it's not configured via GPO according to your first screenshot)

Based on your screens I can't see whether the GPO is applied to the user or computer.
The settings are user based and thus must be assigned to a user.
All GPO settings should be reflected on the client side within the registry at
HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings\

"gpupdate /force" on client side should generate all the configured settings within the registry
as long as the user has assigned that GPO.

Greetings, Thomas
