### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by omurphy522** [HoffmannTom/outlookbackupaddin#11]
Hello,

Quite possibly i am being dense and this is something im doing wrong. 

I am having issues installing since i cannot find setup.exe in the zip folder.

This app rocks and im glad you are still supporting it. 

Thank you

**Comment by HoffmannTom** [comment]
Hello,
in github you must go to Code --> releases
https://github.com/HoffmannTom/outlookbackupaddin/releases
There is a download package which contains an msi file.
Just start the msi file to let windows do the installation steps.

Greetings,
Thomas

**Comment by omurphy522** [comment]
Thank you for the quick response!
