### ISSUE TITLE
Syntax of multiple post-backup commands

### ISSUE THREAD

**Issue by Len44** [HoffmannTom/outlookbackupaddin#13]
Thank you for this add-on. Wonderful!
If I want to run all three of your bat scripts, how do I separate the filenames?

**Comment by HoffmannTom** [comment]
Hello,
you must combine the scripts to just one script. 
Two of the scripts are renaming the files, so you must take care how to combine them.
One script adds the date and the other one a revision number. So you should 
take care of both renaming operations in that loop.
the scripts are just to get an idea how it works and how to develop own scripts

Greetings,
Thomas
