### ISSUE TITLE
10 second delay before starting backup and cancel button

### ISSUE THREAD

**Issue by Dolphin2001** [HoffmannTom/outlookbackupaddin#15]
Hello,
because my backups take up to 8 minutes and it consumes a lot of network power it is unpleasant when I close outlook and the backup starts unintended immediately without any change to stop it. Could you think about putting a 10 seconds count down on a dialog with a cancel button with shifts the backup to the next closing of outlook?
Best regards
D.

**Comment by HoffmannTom** [comment]
Hello,
you can set a countdown before backup starts.
Please nagivate in registry to:
Computer\HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings
Set "CountdownSeconds" to a value greater than 0 (REG_DWORD entry, if not present already).

Greetings,
Thomas

**Comment by Dolphin2001** [comment]
thank you,

great tool.
