### ISSUE TITLE
Add in cannot find path to backup directory

### ISSUE THREAD

**Issue by TeflonGrizzly** [HoffmannTom/outlookbackupaddin#17]
I have one user who's backup add in, after being set up and working properly for approx a week.  Suddenly cannot find the directory.  Re-choosing the same directory fixes the issue for approx a week.  This has happened 3 times to the same user.   

![backup add in error](https://user-images.githubusercontent.com/31519281/39248735-deda720a-486a-11e8-9ed5-bc194c3cd697.png)

**Comment by HoffmannTom** [comment]
Hello,
any updates about this topic?
I will close this issue within the next week if no further information follows.

Thanks!
Thomas

**Comment by HoffmannTom** [comment]
Closed due to missing feedback
