### ISSUE TITLE
Backin Addin not available after install

### ISSUE THREAD

**Issue by dezzo77** [HoffmannTom/outlookbackupaddin#18]
Hello,

I have installed the Backup Addin 1.7, but it does not appear on the Outlook 2016 Pro Plus toolbar.
Also checked the disabled add-ins settings area, and it's not disabled there.

Any idea why it would not be appearing?
I previously had it installed with a different edition of Office on the same machine.  I uninstalled the old Office without uninstalling the Backup addin first.  I tried a repair and uninstall/reinstall of the Backup Addin, but it still won't appear even though it reinstalls normally.  Something is corrupted somewhere.

**Comment by HoffmannTom** [comment]
Hello,
is the plugin listed within outlook --> file --> options --> Add-ins?
You can open command prompt and run:
backupexecutor.exe /register
this will also show information about the found outlook.
Maybe there are some leftovers of the old outlook within the registry.
Do you have 32 or 64 bit outlook?
Outlook is located via:
HKEY_LOCAL_MACHINE\Software\Classes\Outlook.Application\CLSID\
HKEY_LOCAL_MACHINE\Software\Classes\CLSID\<clsid from above>\LocalServer32

Maybe you can try this and take a look at the registry.

Greetings,
Thomas

**Comment by dezzo77** [comment]
Hi Tom,

I have uninstalled and reinstalled the Backup Addin.
The installed edition of Office has been changed previously from 2010 to 2016.
All historical Office keys were manually removed via the command line, and the official cleanup utility tidied up afterwards.

The current version is 64-bit.  I cannot recall what the previous 2010 version was, but I suspect it was 32-bit. 

I tried running the "backupexecutor.exe /register" command from the Admin-CMD prompt inside the host folder, but it said it "was not recognized as an internal or external command, operable program or batch file."

I went to the LocalServer32 key and it was pointing to:
@="C:\\PROGRA~2\\MICROS~1\\Office14\\OUTLOOK.EXE"
"LocalServer32"=hex
That folder does not currently exist on my system.

So, clearly that is wrong.
What do you think?

**Comment by HoffmannTom** [comment]
Hello,
you must change to the installation directory (via cd ...) before calling BackupExecutor.exe.
I recommend to fix the broken directory entry at LocalServer32. Edit the value and enter the correct path to outlook.exe.
Afterwards open cmd, navigate to the installation directory and use the parameter /register as mentioned in the first post.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
any updates about this topic?
I will close this issue within the next week if no further information follows.

Thanks!
Thomas

**Comment by HoffmannTom** [comment]
Closed because of missing feedback
