### ISSUE TITLE
Error: "Failed to copy file: The parameter is incorrect"

### ISSUE THREAD

**Issue by SurrPurr** [HoffmannTom/outlookbackupaddin#19]
I am getting this error in Outlook 2016 Version 1804.  Below is a copy of the log:

Starting backup...please wait...
Check whether outlooks is still running ...
Found outlook with PID 4484
Waiting for OUTLOOK...
No outlook process found
Ensure only one instance running ...
Check whether target directory exists...
Summing up file sizes ...
Total bytes calculated...
Evaluate destination path...
copy C:\Users\hblalock\Documents\Outlook Files\Outlook.pst to D:\Outlook Backup\Outlook.pst
Getting file lock...
Starting copying...
Failed to copy file: The parameter is incorrect

I have tried uninstalling, unregistering, and reinstalling version 1.7 however the error stays the same.  Initially we had a problem as the drive letter for the backup location changed when we switched to a new USB drive.  Once that was corrected this error occurred.

Thanks in advance, and help is appreciated.

**Comment by HoffmannTom** [comment]
Hello,
there are several possible causes for this error:
1) Your pst-file is bigger than 4 GB and your target device is formatted with Fat or Fat32
2) The target device has not enough free disk space left
3) The file system of the target device might be corrupted. Try chkdsk to fix the issue

Hope this helps to narrow down the issue.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
any updates about this topic?
I will close this issue within the next week if no further information follows.

Thanks!
Thomas
