### ISSUE TITLE
Missing Setup.Exe

### ISSUE THREAD

**Issue by JLSencal** [HoffmannTom/outlookbackupaddin#20]
A couple of the links to the outlookbackuppaddin done't have the setup files on them... Finally found one that had it.

**Comment by HoffmannTom** [comment]
Hello,
you must click on "release" tab to get a precompiled msi file.
https://github.com/HoffmannTom/outlookbackupaddin/releases
The zip files contains the installable msi file.

Greetings,
Thomas

**Comment by JLSencal** [comment]
Thanks.... got it!

**Comment by HoffmannTom** [comment]
Hello,
you must click on "release" tab to get a precompiled msi file.
https://github.com/HoffmannTom/outlookbackupaddin/releases
The zip files contains the installable msi file.

Greetings,
Thomas
