### ISSUE TITLE
codeplex Failed to copy file

### ISSUE THREAD

**Issue by JLSencal** [HoffmannTom/outlookbackupaddin#21]
Anyone know how to fix this...

In the last few days i got this message when attempting to backup outlood with Codeplex

codeplex Failed to copy file: The process cannot access the file because another process has locked a portion of the file

I already reset Advanced System Settings, temp files in Environmental Variables to c:\windows
temp

But that didn't work?

I am a low-tech person, not a coder.

Please advise.

**Comment by HoffmannTom** [comment]
Hello,
have you installed the latest version 1.7?
The latest version should show a bunch of helpful information about the progress.
Could you install the latest version and send a 1:1 copy of the output which is diplayed in the window?

If the source file (.pst) is locked by another program, you can use ProcessExplorer from Microsoft:
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
Click "find" --> "find Handle" and enter the path to the locked pst file. 
After searching it should show which program prevents the backup. Some ppl reported that Skype can also lock a pst file. in the background.

Greetings,
Thomas
