### ISSUE TITLE
Outlook 2019 - add-in not showing up in outlook

### ISSUE THREAD

**Issue by vulliw** [HoffmannTom/outlookbackupaddin#23]
Outlook 2016 Backup Add-In 1.7.0 no longer works with X64 !
 I have installed it, not give an error message
 but there is no backup in Outlook 2019 x64 (ribben)

In Outlook 2019 x32 it just works
 Please help me

vulliw

**Comment by HoffmannTom** [comment]
Hello,
please check whether the extension is loaded.
It looks like outlook didnt load the extension.
Check: File --> Options --> Add-Ins --> COM Add-Ins
The backup plugin should be listed in the popup window. Verify, whether the corresponding checkbox is activated.

Greetings,
Thomas

**Comment by vulliw** [comment]
Hello Thomas,

 

I have all checked this

after installation the files are just in the c:\Program Files (x86)\CodePlex\outlookbackupaddin\

The backup plugin should be listed in the popup window !!!    is not there  so I can not check it (Codeplex.BackupAddin – Plugin)

 



 



 

I hoop you can help me

 

thank you in advance

 

Vulliw

 

 

 

 

Van: HoffmannTom <notifications@github.com> 
Verzonden: maandag 8 oktober 2018 23:47
Aan: HoffmannTom/outlookbackupaddin <outlookbackupaddin@noreply.github.com>
CC: vulliw <vulliw@w-vullings.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [HoffmannTom/outlookbackupaddin] Outlook 2019 (#23)

 

Hello,
please check whether the extension is loaded.
It looks like outlook didnt load the extension.
Check: File --> Options --> Add-Ins --> COM Add-Ins
The backup plugin should be listed in the popup window. Verify, whether the corresponding checkbox is activated.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
please try to register the add-in manually via console.
Open cmd.exe, change directory to installation folder, run "BackupExecutor.exe /register" to register the add-in manually.
This should add some registry entries to
HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\

Greetings,
Thomas

**Comment by vulliw** [comment]
Hello Thomas,

 

Yes yes, its now working !!!!

this is the best outlook pst backup program

 

Thanks

 

vulliw

 

Van: HoffmannTom <notifications@github.com> 
Verzonden: dinsdag 9 oktober 2018 13:58
Aan: HoffmannTom/outlookbackupaddin <outlookbackupaddin@noreply.github.com>
CC: vulliw <vulliw@w-vullings.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [HoffmannTom/outlookbackupaddin] Outlook 2019 (#23)

 

Hello,
please try to register the add-in manually via console.
Open cmd.exe, change directory to installation folder, run "BackupExecutor.exe /register" to register the add-in manually.
This should add some registry entries to
HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\

Greetings,
Thomas
