### ISSUE TITLE
Outlook 2016

### ISSUE THREAD

**Issue by Rebbetzin1** [HoffmannTom/outlookbackupaddin#24]
It was working perfectly, and still works on my laptop, but somehow Office Home & Business 2016 wasn't working properly, I reinstalled, and now can't install the OutlookBackupAddIn to my Outlook - I downloaded 1.7, but it doesn't show as an Add-In, and when I go to Options Add-Ins Manage(Go) and then Add I can't add any of the dll files - I just get a message that it's not a valid Office Add-In.  Help.  This is the greatest pst auto backup program ever since Outlook drop theirs.

**Comment by Rebbetzin1** [comment]
No, it's not visible there.
I tried re-registering the add-in as described in #23 first - I finally figured out how to go the right directory, but then it said Registry access not allowed, please run as administrator.  Sorry for my ignorance, but how do I do that?

**Comment by HoffmannTom** [comment]
Hello,
please open cmd.exe as Administrator.
(search for cmd, right click, run as administrator)
Change to the mentioned directory via e.g.:
`cd "c:\Program Files (x86)\CodePlex\outlookbackupaddin\"`
From this folder run:
`BackupExecutor.exe /register`

Greetings,
Thomas

**Comment by Rebbetzin1** [comment]
While you were writing that I actually did figure it out and did exactly that.  Thank you thank you thank you so much - this backup program is just absolutely terrific.  Thanks.
