### ISSUE TITLE
Outlook 2016 disables the plugin automically because it slows down outlook 2016

### ISSUE THREAD

**Issue by Shuklvivek** [HoffmannTom/outlookbackupaddin#25]
Outlook 2016 32bit + windows 10 64bit environment.

Plugin installs, but it gets disabled by outlook 2016 resilency feature.
As it slows starting outlook2016.

Is it possible to avoid slowness of plugin while loading outlook 2016

**Comment by HoffmannTom** [comment]
Hello,
as the add-in uses .Net Framework, it takes a while till outlook initializes the framework and load the DLL.
If the computer is busy it might lead to a delay which is enough for outlook to disable the add-in.
There are some hints to prevent this:
https://docs.microsoft.com/en-us/office/vba/outlook/concepts/getting-started/support-for-keeping-add-ins-enabled
You can use the registry and add the add-in to the key "DoNotDisableAddinList" as described at that website.

Greetings,
Thomas
