### ISSUE TITLE
Cant get add-in to activate - no "Backup" on the ribbon.

### ISSUE THREAD

**Issue by erew123** [HoffmannTom/outlookbackupaddin#26]
I am working on a family members Windows 10 w/Outlook 2013 x64 Pro Plus. The 1.7 Add-in is listed within Outlook, however, always unchecked. If you check it, it un-checks immediately after you OK'ing the add-in window, without even re-starting outlook (all other add-ins keep the setting you specify).

Ive done everything I can find in the help on Github:

- Uninstalled/reinstalled.
- Disabled AV etc.
- Disabled other ad-ins.
- Checked the Event logs (cant find anything relevant).
- Re-registered the add-in at an admin command prompt, which says:
**Detected Office 64 Bit
Fetching Software\Microsoft\Office\Outlook..
Creating subkey Addins
Creating subkey Codeplex.BackupAddIn**
- Hunted the registry to see if Outlook is stating this addin has crashed or something and is disabled (no it hasnt)
- The add-ins within the HKLM\Software\Microsoft\Outlook area does exist (which is backed up by Outlook showing the add-in within the interface).
- Checked the OST and PST files for permissions (the user is Owner and has full control on both files).

The one and only one thing I cannot find is a regkey that back in October last year, on a post on here, its suggested HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\ should be created, and it doesnt exist. Ive run the command line util with /register multiple time, from both Command Prompt and Powershell Admin Prompt (not that it should make a difference).... but nothing works to create this regkey.

Everything else on the machine seems to check out..... Has anyone any suggestions at all? Or perhaps a regfile/list of what should be in that regkey HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\

Thanks!

**Comment by HoffmannTom** [comment]
Hello,
if you have office 64 Bit, the registered plugin is listed within the registry at:
HKLM\SOFTWARE\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn\
Four entries are sufficient there:
- Description
- FriendlyName
- LoadBehavior --> 3
- Manifest

Please verify that you have outlook 64 Bit (e.g. via task manager)
If outlook deactivates the addin, it usually means that it was blacklisted by outlook.
Search for "Codeplex.BackupAddIn" within the registry and delete any other entry, except the one mentioned above.
Or you can delete every entry with this string and re-register it via command prompt.

Hope this helps,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
do you have any news about this issue?
If not, I will close this issue within one week.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Closed due to inactivity
