### ISSUE TITLE
Bitte um Hilfe (Policy)

### ISSUE THREAD

**Issue by Holzschorsch** [HoffmannTom/outlookbackupaddin#29]
Hallo,

die Gruppenrichtlinie funktioniert gut, aber ist es möglich, dem User den Zugriff zu den Einstellungen zu verweigern ?

Besten Dank und Grüße
Georg

**Comment by thomass4t** [comment]
Hallo,
aktuell ist es noch nicht vorgesehen, hört sich aber nach einem kleineren Change an.
Ich gucke mir die nötige Anpassung an und geben Ihnen ein kurzes Feedback.
Evtl. könnten Sie das Testen übernehmen.

Viele Grüße,
Thomas

**Comment by HoffmannTom** [comment]
Hallo,
ich habe eine Option im dev-branch implementiert.
Wenn Sie möchten, kann ich Ihnen eine Testversion per E-Mail zusenden.
Sie können das Kontaktformular verwenden, um Ihre Daten zuzusenden.

Grüße,
Thomas

**Comment by Holzschorsch** [comment]
Hallo,

 

sorry das ich mich erst jetzt melde, ich war bis gestern geschäftlich unterwegs.

 

Wäre super, wenn sie mir eine Testversion übersenden können.

 

Selbstverständlich, bezahlen wir Ihre Arbeit. Bitte teilen Sie uns vorher mit, welche kosten entstehen würden.

 

Besten Dank

 

Manfred Zeitler

 


Gesendet: Sonntag, 05. Mai 2019 um 23:47 Uhr
Von: "HoffmannTom" <notifications@github.com>
An: HoffmannTom/outlookbackupaddin <outlookbackupaddin@noreply.github.com>
Cc: Holzschorsch <holzschorsch@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [HoffmannTom/outlookbackupaddin] Bitte um Hilfe (Policy) (#29)


Hallo,
ich habe eine Option im dev-branch implementiert.
Wenn Sie möchten, kann ich Ihnen eine Testversion per E-Mail zusenden.
Sie können das Kontaktformular verwenden, um Ihre Daten zuzusenden.

Grüße,
Thomas

**Comment by HoffmannTom** [comment]
Released with version 1.9
