### ISSUE TITLE
Version 1.7.0 appears as 1.6.0 in Programs and Features / Win 10 Pro x64

### ISSUE THREAD

**Issue by Phalebote** [HoffmannTom/outlookbackupaddin#3]
After removing version 1.6.0 in Programs Features in preparation for installing version 1.7.0, I installed version 1.7.0. After installing 1.7.0 I checked Programs and Features and found it appears as version 1.6.0.

![image](https://user-images.githubusercontent.com/29687476/27515087-79e62c0e-5969-11e7-9fb8-4c7e6bfb019b.png)

This backup tool is amazing and I **really** appreciate all the hard work you put into it. Thank you so much!!
Phalebote

**Comment by HoffmannTom** [comment]
Hello,
did you download the installer from the new github site or the old Codeplex Site?
The download package on github has already fixed the wrong version number.
Greetings,
Thomas

**Comment by Phalebote** [comment]
We downloaded it from the GitHub site. I had the codeplex page bookmarked in by browser, but it sent me to this GitHub page instead. Just for sake of clarification I'll download the plug-in again from the GitHub site and then test once more. Please stand by.

**Comment by Phalebote** [comment]
I stand corrected. I re-downloaded from GitHub and version looks correct now. Must have mixed up my 1.6.0.0 files and 1.7.0.0 files since they are both named the same name (OutlookBackupAddIn.msi).
![image](https://user-images.githubusercontent.com/29687476/28216775-cadf9426-6880-11e7-9733-ce7a14115066.png)

Closing my made-up issue thread :). Thanks for the help.
