### ISSUE TITLE
PST size

### ISSUE THREAD

**Issue by lanjekarraj** [HoffmannTom/outlookbackupaddin#30]
This tool is excellent and works well.

Is it possible to add some feature, to show the size of PST.

Which will inform user, if the PST grows beyond a particular size.

You can give it a thought.

Cheers !

**Comment by HoffmannTom** [comment]
Hello,
this sounds reasonable. I would also like to know the file size :)
It's implemented in the development branch and will be included in the next release.

Greetings, Thomas

**Comment by lanjekarraj** [comment]
Thank you for your positive response as always.

i feel giving user an option in settings to specify PST size in GB alert threshold will make it more effective.

alert can be an exptra pop up if file size exceeds this limit.

**Comment by HoffmannTom** [comment]
Hello,
I think a backup program should not be responsible for warning about reaching a certain file size.
If the mailbox size is limited, the mailbox system should warn (as MS exchange and other providers do).
If the backup space is limited, the backup space provider should warn.
In general the backup space should be larger than the maximum mailbox size.

Therefore I think the responsibility should be clearly separated and the outlook add-in should not know about any size limitations other systems have. It's the responsibility of the other systems.

Greetings, 
Thomas

**Comment by lanjekarraj** [comment]
Even if the size is displayed in GB, in the backup window, it may help.

**Comment by HoffmannTom** [comment]
Released with version 1.9
