### ISSUE TITLE
Outlook 2019 Add in compatiblity

### ISSUE THREAD

**Issue by EdouardLi** [HoffmannTom/outlookbackupaddin#31]
Hello,

Thank you for great works on this add-in.
Could you please tell me if it will be a support of Office 2019 ?

Regards,
Edouard Li.

**Comment by HoffmannTom** [comment]
Hello Edouard,
the add-in also works also with Office 2019 (local installation).
The setup works for 32- and 64-bit version.

Greetings,
Thomas

**Comment by EdouardLi** [comment]
Hello,

Thank you for your reply.

Regards.

Le mar. 16 juil. 2019 à 20:06, HoffmannTom <notifications@github.com> a
écrit :

**Comment by HoffmannTom** [comment]
I updated the wiki page and added 2019 as supported office version.
