### ISSUE TITLE
Immediate Backup.

### ISSUE THREAD

**Issue by Mallorca1946** [HoffmannTom/outlookbackupaddin#32]
Nice to have...  in the Backup tab in Outlook in addition to Settings a "Backup Now" selection which causes an immediate backup when Outlook ends (rather than as per the schedule).  For use when very important emails arrive which you want to preserve immediately.

**Comment by HoffmannTom** [comment]
Hello,
there is already such function available. Just open the settings dialog and click "reset".
This will trigger the backup when outlook is closed.
This requires one click more but should do the trick.

Greetings,
Thomas

**Comment by Mallorca1946** [comment]
Hi… Tried that and on closing Outlook got a bunch of messages in the pop-up generated by outlookbackupaddin stating… “Waiting for Outlook” and “Error”.

 

Cheers… Les Paton

Be bold, or even italic, but never regular.

**Comment by Mallorca1946** [comment]
Hi… Found the problem….AVAST A/V was blocking the exe.

 

Cheers… Les Paton

Be bold, or even italic, but never regular.

**Comment by Mallorca1946** [comment]
OK, doing a Reset works fine.  However, that's 4 keystrokes... Backup/Settings/Reset/Save  ... vs 2 for my suggestion...  Backup/Backup Now.
AVAST A/V after putting the exe on inspection has now cleared it as safe.

**Comment by HoffmannTom** [comment]
Hello,
the button is available in the development branch.
It will be included in the next release.

Greetings,
Thomas
