### ISSUE TITLE
Backup Stuck @ Summing up file sizes ...

### ISSUE THREAD

**Issue by lanjekarraj** [HoffmannTom/outlookbackupaddin#33]
We recently upgraded from 1.7.0 to 1.9.0, on Windows 10 (64 bit), with Outlook 2016 32 bit.

We have not prob with 1.7.0, but 1.9.0 we get this message, and it never proceeds to backup.

10:25:59 Starting backup...please wait...
10:26:00 Check whether outlooks is still running ...
10:26:00 Found outlook with PID 19476
10:26:00 Waiting for OUTLOOK...
10:26:00 Found outlook with PID 19476
10:26:00 Waiting for OUTLOOK...
10:26:01 Found outlook with PID 19476
10:26:01 Waiting for OUTLOOK...
10:26:02 No outlook process found
10:26:02 Ensure only one instance running ...
10:26:02 Check whether target directory exists...
10:26:02 Summing up file sizes ...
10:26:02 Adding size of C:\Data\Mail\MS Exchange.pst (1.33 GB)

Any clue what is causing this ?

**Comment by lanjekarraj** [comment]
This may help

C:\Program Files (x86)\CodePlex\outlookbackupaddin>10:40:03 Starting backup...please wait...
10:40:03 Check whether outlooks is still running ...
10:40:03 No outlook process found
10:40:03 Ensure only one instance running ...
10:40:03 Check whether target directory exists...
10:40:03 Summing up file sizes ...
10:40:03 Adding size of C:\Data\Mail\MS Exchange.pst (1.33 GB)
Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at BackupExecutor.BackupTool.GetFileLength(String path)
   at BackupExecutor.BackupTool.doBackup(BackupSettings config, Logger log)
   at BackupExecutor.BackupTool.tryBackup(BackupSettings config, Logger log)
   at BackupExecutor.Program.Main(String[] args)

**Comment by HoffmannTom** [comment]
Hello,
version 1.9 is more talk-active to track down issues more easily.
In your case there is an error:
"The system cannot find the file specified"
So the first question is, whether there is a file "C:\Data\Mail\MS Exchange.pst" ?
Does this file exist? 
If no, then it was previously selected for backup but doesnt exist any more. 
In that case you need to go to the settings tab and update and files which should be backuped.

Greetings,
Thomas

**Comment by lanjekarraj** [comment]
The PST is very much there "C:\Data\Mail\MS Exchange.pst" ?

Infact i simply uninstalled 1.9.0 , and installed 1.7.0. Backup works in 1.7.0
It only finds a prob with 1.9.0..

**Comment by HoffmannTom** [comment]
Hello,
i put a pst file at exactly the same location and also used the filename with blank in it.
Unfortunately i cant reproduce the error.
Is there any symbolic link, junction, activated encryption, compression, ... within that path?
If you want to track down the issue, you can use ProcMon.exe from the sysinternal tools.

Nevertheless the next version wont stop the backup when it cant sum up the file sizes to display the
progress bar.

Greetings, Thomas

**Comment by Mallorca1946** [comment]
I got those same messages after installing 1.9.0 and it was caused by AVAST A/V blocking the exe file and opening an inspection on it as a possible threat.  I selected "run anyway" in the A/V.  They later cleared it as safe.  Check your A/V.

**Comment by lanjekarraj** [comment]
Nothing is getting logged in A/V.

Do you want to have a look in remote session ?

**Comment by HoffmannTom** [comment]
@Mallorca1946: Thanks for the hint with the anti virus ... might be a possible reason
@lanjekarraj : If you like to investigate it, we can do a remote session. You can drop a line via contact form to arrange a teamviewer meeting for example.

**Comment by lanjekarraj** [comment]
arrange a teamviewer meeting at you convenience.
I am available
Mon-Fri 9am to 5 pm (+5:30 GMT timezone).
weeends please give atleast 1 hour prior intimation, to hook on online, if you are available.

**Comment by HoffmannTom** [comment]
Hello,
due to the time difference i would suggest weekend.
Please drop a line via contact form to exchange further information.

Thanks! Thomas

**Comment by HoffmannTom** [comment]
Hello,
if you are available today, you can drop a line. Just send time and teamviewer-id via contact form.
Thanks! Thomas

**Comment by HarryAudus** [comment]
Hi Tom
 
Thanks for your enthusiastic attention. I’ve decided it’s all too hard. I’ll stick with just backing up calendar and contacts to pst files.
 
Harry
p 0432 079 251       e  <mailto:harry@audus.com> harry@audus.com

**Comment by HoffmannTom** [comment]
Hello,
its up to you. If i get similar reports, i will let you know.
Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
I just could reproduce that issue. Please download current version from
https://github.com/HoffmannTom/outlookbackupaddin/releases/tag/1.9
This should fix the issue.
Greetings,
Thomas

**Comment by HarryAudus** [comment]
Hi Tom
 
Thanks for your persistence. I have downloaded and installed your latest version, but it only gives the option of backing up a pst file, not any folders in my ost files. Is this intentional?
 
Harry
p 0432 079 251       e  <mailto:harry@audus.com> harry@audus.com

**Comment by lanjekarraj** [comment]
It started now.

**Comment by HoffmannTom** [comment]
Hello,
for ost files please check the wiki page
https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)
Greetings,
Thomas
