### ISSUE TITLE
backup settings greyed out

### ISSUE THREAD

**Issue by HarryAudus** [HoffmannTom/outlookbackupaddin#34]
This addin looks very promising, but after I'd installed it, the Backup tab appears in the ribbon but is greyed out, i.e. I can't use it. What haven't I done?

**Comment by HoffmannTom** [comment]
Hello,
could you please take a look at the registry settings at:
Computer\HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings\
Is there a key named "AllowSettingsAccess" ?

Greetings,
Thomas

**Comment by HarryAudus** [comment]
Hello Tom
 
Thanks for your quick reply. I don’t even have a CodePlex folder under HKEY_CURRENT_USER\Software.
 
Happy Thursday.
 
Harry
p 0432 079 251       e  <mailto:harry@audus.com> harry@audus.com

**Comment by HoffmannTom** [comment]
Hello Harry,
thanks for that information. I could track down the issue.
I uploaded a new setup. Alternatively you can create that registry key. Then it will also work.

Thanks for your reportl
Thomas

**Comment by HoffmannTom** [comment]
Hello,
did it work?
If there are no further comments or replies within the next 2 weeks, I will close this issue.
Greetings,
Thomas
