### ISSUE TITLE
GPO Problem "Destination path of backup"

### ISSUE THREAD

**Issue by MunichzFinest** [HoffmannTom/outlookbackupaddin#35]
Hello,

thanks for for this great tool.
We are currently using and testing the GPO abilities.
Most of it is working as expected but if we provide a Backup path over the "Destination path of backup" option the path is not reachable.
Sample Path: `\\Server\pst$\%username%`
The Path is correctly shown in the setting but if we save it always state: Destination-folder doesn't exists!

If I delete it and type exactly the same manually it works without issues. If I copy the path line from the settings window and copy it to a explorer windows it also fails. If I type it by hand again it's working. Also if I copy it first to notepad and then to the explorer or back to the Destination Line it fails.

Means from the appearance it's absolutely same but the effect is different.

This option would be really handy for us so I hope it is a solveable issue.

Thanks in advance.

**Comment by MunichzFinest** [comment]
Now it's working. Don't know why - actually we checked for hidden blanks etc. before more than twice.
Nevertheless I noticed that in the GPO Setting are many blanks by default which need to be deleted before.
![image](https://user-images.githubusercontent.com/53869440/62635678-6678a300-b938-11e9-8bfb-e27f17227475.png)

**Comment by HoffmannTom** [comment]
Hello,
the whitespaces might origin from a linebreak in the file
OutlookBackupAddin.adml
You can modify it, its just a XML file.
The GPO templates are just a configuration file to edit the registry. 
You can compare and check the settings on client side within the registry at:
Computer\HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings\

the whitespaces will be remove in one of the next versions.

Greetings,
Thomas
