### ISSUE TITLE
Error retrieving file size

### ISSUE THREAD

**Issue by AlDum2** [HoffmannTom/outlookbackupaddin#36]
Hello,
I installed latest version 1.9 (downloaded 31/07/2019) and when exiting Outlook 2013 (on W10) I get the following errors for each of the PST I would like to backup (for test purposes I backup to another folder on the same drive):
17:48:51 Starting backup...please wait...
17:48:51 Check whether outlooks is still running ...
17:48:51 No outlook process found
17:48:51 Ensure only one instance running ...
17:48:51 Check whether target directory exists...
17:48:51 Summing up file sizes ...
17:48:51 Adding size of C:\xxx\Outlook\ZZZ-G.pst (495,53 MB)
17:48:51 Error retrieving file size from: -C:\xxx\Outlook\ZZZ-G.pst (495,53 MB)-
17:48:51 Adding size of C:\xxx\Outlook\BNL-DemandManagement.pst (710,35 MB)
17:48:51 Error retrieving file size from: -C:\xxx\Outlook\BNL-DemandManagement.pst (710,35 MB)-
17:48:51 Adding size of C:\xxx\Outlook\ADU-WAN.pst (494,56 MB)
17:48:51 Error retrieving file size from: -C:\xxx\Outlook\ADU-WAN.pst (494,56 MB)-
17:48:51 Adding size of C:\xxx\Outlook\ADU-Telephony.pst (14,06 MB)
17:48:51 Error retrieving file size from: -C:\xxx\Outlook\ADU-Telephony.pst (14,06 MB)-
17:48:51 Adding size of C:\xxx\Outlook\ADU-Sites.pst (965,38 MB)
17:48:51 Error retrieving file size from: -C:\xxx\Outlook\ADU-Sites.pst (965,38 MB)-

Any idea how to correct this?

Regards,
Al

**Comment by HoffmannTom** [comment]
Hello,
could you please download the current setup?
There was a bug which messed up the configuration.
After installing the current version you must configure the pst files again to fix this issue.

Thanks!
Thomas

**Comment by HoffmannTom** [comment]
Hello,
any updates on this issue?
If there are no further comments / replies within the next 2 weeks, I will close this issue.

Greetings,
Thomas

**Comment by Jarekxc** [comment]
Hello 

Is there any solution for this error ?

Greetings,

**Comment by thomass4t** [comment]
Hello,
the solution was to download the latest zip-file and install that one.
(the same version number was superseeded).
If you still have this issue after installing the latest download, please post the error message here.

Greetings, Thomas

**Comment by AlDum2** [comment]
Hello,
Sorry for the delay. 
I tried with the latest version, but now I get an error at install:
"Error reading from file
c:\XXXXXXX\Downloads\MSOutlook2013PstBacku\OutlookBackupAddIn.msi. Verify that the file exists and that you can access it."
The file is the msi I just started.
I tried redownloading the package, same result.
Any idea?
Greetings,
Alain

**Comment by HoffmannTom** [comment]
Hello, 
this means that the system (msi installer) cant access this msi file.
Probably it is due to missing permissions on that folder:
https://decisionstats.com/2014/03/25/windows-7-error-verify-that-the-file-exists-and-that-you-can-access-it/

You can try to change the permission or copy the msi file to another location where it can be accessed by the msi installer process.

Regards, Thomas

**Comment by AlDum2** [comment]
Issue solved!
Thank you, it works great!
