### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by omurphy522** [HoffmannTom/outlookbackupaddin#37]
![Annotation 2019-08-20 103129](https://user-images.githubusercontent.com/8385953/63356449-cf4b1c80-c335-11e9-930b-dab35da92df1.png)

I am getting an error when trying to install on a new PC it is running windows 10 Pro any idea where I can look to try to resolve this issue?

**Comment by HoffmannTom** [comment]
Hello,
you can configure a logfile via the msi-installer.
A brief introduction is shown here:
https://www.advancedinstaller.com/user-guide/qa-log.html

It might be, that the setup cant find your outlook installation.
More details should be shown in the logfile.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Just a quick note:
The installer tries to find the installation location of outlook via registry via one of these entries:
HKLM\Software\Classes\Outlook.Application\CLSID
HKLM\Software\Classes\Outlook.Application.<version>\CLSID

If none of these registry key exists, the setup might fail.
Greetings, Thomas

**Comment by SolomonCM** [comment]
this is caused by having the M$ store version of office365/outlook installed. I prepared a more detailed posting a few minutes ago about the issue. the traditional office outlook, and the store version of office outlook may look and operate the same, but their dependencies and file locations are slightly different.

**Comment by omurphy522** [comment]
Thank you.

I found out the other day that reinstalling office fixed the issue.

Thank you,

Owen

**Comment by SolomonCM** [comment]
unfortunately reinstalling in my case won't help. I have had this issue across two system reformats, and 4 reinstalls of the ms-store version of office outlook

**Comment by HoffmannTom** [comment]
ms-store version is tracked by that issue:
https://github.com/HoffmannTom/outlookbackupaddin/issues/42
The topic of this ticket was solved.
