### ISSUE TITLE
No file location shown in Outlook-Files box

### ISSUE THREAD

**Issue by gwlane** [HoffmannTom/outlookbackupaddin#38]
I'm moving to a new laptop and used the OutlookBackupAddin file that I used on my previous laptop but when I go to setup the backup options, there are no file locations listed under Outlook-Files. I uninstalled and downloaded the latest app (1.9) and tried again, but nothing shows. I tried to unhide hidden directories, but that didn't work either. The error I get indicates no files for backup selected. Any ideas would be greatly appreciated. I'm using Outlook 2013 just as I have on my previous laptop. OS is Windows 10 just as it is on my previous laptop. 

Thanks in advance for your assistance.

**Comment by HoffmannTom** [comment]
Hello,
this pane only shows accounts, which are configured as POP/SMTP accounts.
IMAP and Exchange accounts wont be listed.
Could you check, wich types your configured accounts have?

Greetings,
Thomas

**Comment by gwlane** [comment]
The account is an IMAP account which is the same type of account on my previous laptop. This is what it looks like on my previous laptop:



 

My new laptop doesn’t show the file location, but the Outlook accounts are both IMAP/SMTP

 

George W. Lane

225 Spring Tyme Court

Lexington, SC 29073

 

gwlane1@twc.com

 

C. 803-586-6527

**Comment by HoffmannTom** [comment]
Hello,
the screenshots got lost somehow.
Can you check, whether you have ost or pst files?
Please also take a look at the documentation:
[Wiki](https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F))

Greetings,
Thomas

**Comment by gwlane** [comment]
Hi Tom, 

 

Hopefully you will be able to view the pictures that I have included. 

 

The first set are of my older laptop with the same version of Outlook and Windows 10. This system is working as it should. The pictures labeled ‘Old” are of the original laptop. 

 

The other three pictures are from the newer laptop with the latest BackupAddin file. As you can see, this one doesn’t show the location information for the .pst file and therefore fails when trying to do the backup. 

 

Hope this helps. 

 

Thanks for your help. 

 

George Lane

**Comment by HoffmannTom** [comment]
Hello,
still no pictures. Please check on your new computer whether outlook uses pst or ost files!
(In outlook: files --> account settings...)

If you like you can also drop a line via contact form and send me your email.
Then we can exchange images via mail.

Greetings,
Thomas

**Comment by gwlane** [comment]
I’m sorry Tom, 

 

This is ridiculous. Where do I open a contact form on your website so that I can upload the pictures to you. If you can’t see what I’m talking about, you can’t very well help me. 

 

Sorry for the problem. Apparently, Outlook is blocking the pictures. 

 

George W. Lane

225 Spring Tyme Court

Lexington, SC 29073

 

gwlane1@twc.com

 

C. 803-586-6527

**Comment by HoffmannTom** [comment]
Hm... i thought there was a contact form in the past.
I published a mail address on my profile page.
Greetings, Thomas

**Comment by gwlane** [comment]
Hi Thomas, 

 

George Lane again. 

 

I’ve been working on Outlook to try to get it to the place where I can use the Backup program to save the .pst file. I’ve just about gotten it. Here’s the output I’m getting now:

16:10:30 Check whether outlooks is still running ...

16:10:30 Found outlook with PID 5240

16:10:30 Waiting for OUTLOOK...

16:10:31 No outlook process found

16:10:31 Ensure only one instance running ...

16:10:31 Check whether target directory exists...

16:10:31 Summing up file sizes ...

16:10:31 Adding size of C:\Users\gwlane\Documents\OutlookBK\backup.pst

16:10:31 Total bytes calculated...

16:10:31 Evaluate destination path...

16:10:31 Can't copy file on it's own, skipping: C:\Users\gwlane\Documents\OutlookBK\backup.pst

16:10:31 One or more errors occurred. Please check the messages above and close this window manually.

 

What does it mean, “Can’t copy file on it’s own? 

 

I think I’m closer to a clean backup but not sure what the error means. 

 

Thanks in advance for your assistance. 

 

George Lane

**Comment by HoffmannTom** [comment]
Hello George,
the message "Can’t copy file on it’s own" means that the backup destination folder overlaps with one of the pst locations.
Please choose another backup directory where none of the pst files reside.

Greetings,
Thomas

**Comment by gwlane** [comment]
Tom, 

 

Thank you for your help with this. I think I am finally able to successfully use the backup routine and save the .pst file. I appreciate your assistance and patience as I struggled to get this working. 

 

George Lane

**Comment by gwlane** [comment]
Good morning Tom, 

 

George Lane here. I’ve contacted you before concerning the outlookbackupaddin not working for me and you indicated that this worked only with POP email configurations. 

 

https://www.thewindowsclub.com/automatically-backup-outlook-pst-data-file

 

This article seems to indicate that the addin now saves OST files as well. I just downloaded version 1.9 as I had to create a new ID but the previous addin didn’t show the path for backing up the .pst file. 

 

My email account from Spectrum will only create an IMAP account. However, after installing the latest addin, I don’t get the path showing the Outlook Files in the Backup Settings dialog box.

 

Suggestions?

 

Is this newest version able to work with IMAP email configurations?

 

Thanks Tom for your help. 

 

George Lane

**Comment by gwlane** [comment]
Hi Tom, 

 

I just sent you an email asking about the 1.9 OutlookBackupAddin app. After some searching, I understand the difference between the .pst and the .ost files and the reasoning behind it. By the way, I’m using Outlook 2013. 

 

I wanted to ask, if this is a satisfactory work-around. 

 

I manually created a .pst backup and stored it in a directory under my documents folder. (Documents\OutlookBK1)

I opened the email account settings dialog and added the path to the data files tab for the .pst file I just created manually. (C:\users\gwlane1\Documents\OutlookBK1\backup.pst

 

Now the .pst path shows up in the Outlook Backup addin. Settings dialog

So now I set up a path for the backed up .pst file to \Documents\OutlookBK

 

Now when I close Outlook, the backed up file goes to the OutlookBK folder as a .pst file. 

 

Let me know if you think this work around is a satisfactory option when all I have is an IMAP email account. 

 

Thanks again for your help and advice. 

 

George Lane 


Sent: Thursday, August 22, 2019 7:44 AM
To: HoffmannTom/outlookbackupaddin <outlookbackupaddin@noreply.github.com>
Cc: gwlane <GWLANE1@TWC.COM>; Author <author@noreply.github.com>
Subject: Re: [HoffmannTom/outlookbackupaddin] No file location shown in Outlook-Files box (#38)

 

Hello,
this pane only shows accounts, which are configured as POP/SMTP accounts.
IMAP and Exchange accounts wont be listed.
Could you check, wich types your configured accounts have?

Greetings,
Thomas

**Comment by gwlane** [comment]
Hi Tom, 

 

I've been using the Outlook Backup app for some time. I'm on Office 2019 and
have had no problems until recently. For some reason it has started failing
when doing the backup as follows:

 

Can't copy file on it's own, skipping:
C:\Users\gwlane1\Documents\OutlookBK\backup.pst

 

This is a picture of how I have it set up:

 



 

Here's my Data path:

 



 

Don' know why, but it just started acting up. Any ideas?

 

 

Thanks,

 

George Lane

225 Spring Tyme Court

Lexington, SC 29073

 

C. 803-586-6527

***@***.***

**Comment by HoffmannTom** [comment]
Hello,
please don't hijack old, closed issues for new issues.
The message explains the error. The pics are not shown, so I guess you chose the file:
C:\Users\gwlane1\Documents\OutlookBK\backup.pst
to be backed up and its identical to the destination folder.

**Comment by gwlane** [comment]
Tom,

I’m sorry if I’ve done something wrong. Is there a Database of old problems that I can search to see how this was corrected in the past?

 

The answer to your question is, yes. I’ll try to post another picture for you. But the file location is:

C:\Users\gwlane1\Documents\OutlookBK\backup.pst (1GB)

And the destination: C:\Users\gwlane1\Documents\OutlookBK

 

So I’m guessing that you are indicating that the source file and destination file should not be the same?

 

If that’s the case, I don’t know what was changed since it was working for some time and all of a sudden stopped working. 

 

Thanks,

 

George Lane

225 Spring Tyme Court

Lexington, SC 29073

 

C. 803-586-6527

***@***.***

**Comment by HoffmannTom** [comment]
Hello gwlane,
to search old issues, just click on "issues" and adjust the filter.
Your configuration shows the problem. The backup has the same name as the original file.
So you can't backup a file into the same location.
Maybe you opened a backup-pst in outlook and checked the tickmark to backup all pst-files.
