### ISSUE TITLE
Backup not done

### ISSUE THREAD

**Issue by user239393** [HoffmannTom/outlookbackupaddin#39]
Hi, I am using MS Windows 10 64bit, and Outlook 2016. I have a .mail.de account for emails and a .outlook.de account for calendar.
Only a .ost file of the .outlook.de account was created. As far as I understand, this is no backup that can be used to restore my account after new istallation.

**Comment by HoffmannTom** [comment]
Hello,
all about ost and pst file is mentioned in the wiki page:
https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)
It all depends which protocol you use for accesing your mails.
if you have further questions, just drop a line.

Greetings, Thomas

**Comment by HoffmannTom** [comment]
Hello,
do you have any news about this topic? Are your questions clarified?
I will close this issue after 7 days if no further feedback is provided.

Thanks! Thomas

**Comment by HoffmannTom** [comment]
closing this issue because no further information provided.
