### ISSUE TITLE
Failed to copy file: More data is available

### ISSUE THREAD

**Issue by tolispy** [HoffmannTom/outlookbackupaddin#40]
One of my .pst files **is bigger than 4GB**.

The backup works as long the destination file does not exists.
If it does exists then at some point during copying I get "Failed to copy file: More data is available" and the backup stops.

I am using Windows 10 64-bit, Microsoft Outlook 2010 32-bit.

Look at https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfileexa
dwCopyFlags COPY_FILE_NO_BUFFERING and COPY_FILE_RESTARTABLE may fix the problem (not sure).

**Comment by HoffmannTom** [comment]
Hello,
I tried with 4,4 GB file without any problems.
Maybe your target device doesn't support files > 4 GB (e.g. FAT32 formatted Stick or USB-Drive).
I tested with NTFS file system and no issues showed up.

Greetings, Thomas

**Comment by tolispy** [comment]
The target disk is NTFS with enough free space.

I found when it fails.

If the destination folder is uncompressed, it works.
If the destination folder is compressed, it works, if the is no file to override.
If the destination folder is compressed, it fails, if the is file to override.

When I say compressed folder I mean
right click to the folder,
select properties,
click advance button,
check the compress this folder checkbox.

**Comment by HoffmannTom** [comment]
Hello,
there must be something else which causes that error.
I tested with compressed target folder, 5,5 GB file.
It worked also when overwriting the old backup.
Maybe your pst contains a secondary file stream(?)
Can you test with any other large file?
Actually you can backup any file, you can directly edit registry
Computer\HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings
and insert any file in the key "items". Set LastRun to an old date and open/close outlook again.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Maybe you can also send a screenshot of the error message including the output screen of the window.

**Comment by HoffmannTom** [comment]
Hello,
this issue will be closed within 7 days if no further information is provided.
Regards, Thomas

**Comment by HoffmannTom** [comment]
Closed due to missing feedback.
