### ISSUE TITLE
can not install using MS-Store version of outlook

### ISSUE THREAD

**Issue by SolomonCM** [HoffmannTom/outlookbackupaddin#42]
I got a new PC that came with Office 365 trial. M$ apparently has two types of office 365 available for use now. the traditional desktop installed version you get from visiting the M$ office site, and the windows store version which while it operates and looks identical, it is indeed different. the outlookbackupaddin works for the traditiona; desktop install version, but does not work for the ms store version. I did a back door install by installing the traditional version side by side the store version, and I then had two separate copies of all the office programs. 

I tried to use the outlookbackup.vsto to install the addin into the store version, but it calls on files not in the outlookbackupaddin installed files. I found out which files were needed, and fortunately, windows already had copies of the files, all located under various directories in c:\windows\microsoft.net\assembly\gac_msil\

I thought I could copy the files over to the backupaddin directory, but this resulted In a hash mismatch error for Microsoft.visualstudio.tools.applications.runtime.dll

the files which the .vsto reported as missing are as follows:
Microsoft.VisualStudio.Tools.Applications.Runtime.dll
Microsoft.Office.Tools.Common.dll
Microsoft.Office.Tools.Outlook.dll

on my system with only the store version of office installed windows keeps these files in the following locations:
C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.VisualStudio.Tools.Applications.Runtime\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Tools.Applications.Runtime.dll

C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.Office.Tools.Common\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.Office.Tools.Common.dll

C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.Office.Tools.Outlook\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.Office.Tools.Outlook.dll

here is the first error found when I tried to install the addin manually using the .vsto file:

Name: BackupAddIn
From: file:///C:/Program Files (x86)/CodePlex/outlookbackupaddin/BackupAddIn.vsto

************** Exception Text **************
System.Deployment.Application.DeploymentDownloadException: Downloading file:///C:/Program Files (x86)/CodePlex/outlookbackupaddin/Microsoft.VisualStudio.Tools.Applications.Runtime.dll did not succeed. ---> System.Net.WebException: Could not find file 'C:\Program Files (x86)\CodePlex\outlookbackupaddin\Microsoft.VisualStudio.Tools.Applications.Runtime.dll'. ---> System.Net.WebException: Could not find file 'C:\Program Files (x86)\CodePlex\outlookbackupaddin\Microsoft.VisualStudio.Tools.Applications.Runtime.dll'. ---> System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\CodePlex\outlookbackupaddin\Microsoft.VisualStudio.Tools.Applications.Runtime.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.FileWebRequest.GetResponse()
   at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

subsequent errors listed the other file discussed here names as missing.

I suspect fixing this error will allow for a normal install from the .msi setup file to succeed

**Comment by HoffmannTom** [comment]
Hello,
you should not mess around with the global assembly cache. It is quite sensitive to direct changes within the file system.
Could you try to install VSTO at https://www.microsoft.com/en-us/download/details.aspx?id=56961 manually?
This should install the needed dll files within the GAC.

You can register the plugin via command line "BackupExecutor.exe /register"

Greetings,
Thomas

**Comment by SolomonCM** [comment]
ok I will try that

**Comment by SolomonCM** [comment]
I have already installed that, even thought I have O365, since you list that package as a requirement.

**Comment by SolomonCM** [comment]
also tried your "backupexecutor.exe /register" command, but with out modifying permissions to access "c:\program files\WindowsApps\" I can not gain access to the Outlook program file needed for the command to succeed.

**Comment by HoffmannTom** [comment]
Hello,
it is hard to figure out the problem without having that special office version.
Maybe you can try the following:
1) What happens when you run "backupexecutor / register" from command prompt with elevated privileges?
2) You can run msi setup with activated logging as described in:
https://stackoverflow.com/questions/7126077/create-an-msi-log-file
and post the logfile.

Hope this will shed more light about the issue.

Regards, Thomas

**Comment by SolomonCM** [comment]
i backed up file and folder permissions then gained access to the folder with in ..\windowsaps\ that had the outlook.exe, and while the command looked like it succeeded, after starting up outlook, the addin was not added.

**Comment by SolomonCM** [comment]
So which of the two commands do I use? Or do I use both?

**Comment by HoffmannTom** [comment]
??
The link mentions the necessary parameters.
Both lines are syntactically the same (parameter /L for logfile, /i for msi-file).

**Comment by HoffmannTom** [comment]
It seems that the store version of office has some trouble with add-ins in general:
https://www.slipstick.com/outlook/outlook-store-app/#addins
https://www.add-in-express.com/creating-addins-blog/2019/02/27/office-from-store-issues/

**Comment by HoffmannTom** [comment]
Hello,
it seems that Microsoft shifted back to the click-to-run installation:
https://www.windowscentral.com/microsoft-removes-ability-install-office-directly-microsoft-store-windows-10
The license allows users to install also the click-to-run version. Currently thats the only way to use the add-in. Store Apps are restricted regarding file access and running other programms.

Greetings, Thomas

**Comment by SolomonCM** [comment]
Hmm…. My PC came pre-installed with the Store versions of Office 365….. I previously found out that it was possible to have the click to run and the store versions installed at the same time, and that they existed as separate copies. The click to run copy did not have m email account or emails, while the store version still did. If you not going to fix outlook backup add in to work with the store version of office, then I might have to consider switching over to the click to run version……..

**Comment by HoffmannTom** [comment]
Hello,
as the store version is not offered any more and as I dont have that version available for testing, I must unfortunately tell you that there is no option on my side to support the store version.
As this project is open source and if somebody has that office version, he/she could adjust the code accordingly and fork the project or can send a pull request.

Greetings, Thomas
