### ISSUE TITLE
Settings dialog shows no entries

### ISSUE THREAD

**Issue by michael-banco** [HoffmannTom/outlookbackupaddin#44]
After installing the dialog leaves blank. I can fill in entries and save them. But next time i open settings dialog, entries are blank again. I can find reg keys in registry and manually modify them.
After closing Outlook, backup is working fine.

Edit: Its Outlook Home and Business 2016, 16.0.11929.20298 32 bit

![snap0001](https://user-images.githubusercontent.com/55439900/65038121-8051d080-d94f-11e9-9c96-710f4e392398.PNG)
![snap0002](https://user-images.githubusercontent.com/55439900/65038303-f9512800-d94f-11e9-8241-205567f5937d.PNG)

**Comment by HoffmannTom** [comment]
Hello,
please check whether you have ost-files or pst-Files.
Only the latter one is suitable for taking backups.
You can find more information about that at:
https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)

Greetings, Thomas

**Comment by michael-banco** [comment]
Hi. Only PST-Files.
Regards Michael

**Comment by HoffmannTom** [comment]
Hello,
what do you mean by "I can fill in entries and save them". Do you refer to the registry entries?
Could you provide a screenshot of Datei --> Kontoeinstellungen --> Datendateien?

It looks like the add-in can't get the file paths.
If you want to dig deeper. I could send you a dll which shows extended information
via a popup for each file found.

Greetings,
Thomas

**Comment by michael-banco** [comment]
Hi Thomas.

The first screenshot at the beginning is showing up at every start of outlook and opening settings.

The second start "alle dateien sichern" i checked and manually set the path-settings. The backup started automatically at the ending of outlook, and the list of files and the settings was written into registry.

Now i use only the first of the pst-files, i changed the entry manual in registry.
![grafik](https://user-images.githubusercontent.com/55439900/65500934-5d2f9f80-dec0-11e9-915d-bb05c904d695.png)
![grafik](https://user-images.githubusercontent.com/55439900/65501268-fbbc0080-dec0-11e9-8057-0800dcfc23fb.png)

The backup is nevertheless working.

Michael

**Comment by HoffmannTom** [comment]
Hello,
thanks for the screenshot. This helped to narrow down the issue.
There are two PST-Files with long path name syntax (\\UNC\?\...)
Unfortunately .Net 4.0 can't handle that format. I have to use native Win-Api to get
the file size.
This feature is available in the development branch.
If you like I can send you an updated DLL file which you can replace.
If needed, just drop a line via email so I can send it to you.

Greetings, Thomas

**Comment by michael-banco** [comment]
Hello.
This could cause the problem? Hm, i know, when i installed it, there was a UNC-PST, too. But i can't change it to driveletters, right now.

Michael

**Comment by michael-banco** [comment]
Hi Thomas.

The version you send me is working.

Thank you and regards
Michael

![grafik](https://user-images.githubusercontent.com/55439900/65581814-75fd8b00-df7c-11e9-8c3e-c1d14c743282.png)

**Comment by HoffmannTom** [comment]
Thanks for your reply!
