### ISSUE TITLE
grandfather-father-son backups

### ISSUE THREAD

**Issue by bz12** [HoffmannTom/outlookbackupaddin#46]
Hi. Thanks for creating outlookbackupaddin. Just started using it with Outlook 2019. Question: Is it possible to save daily backups using a grandfather-father-son rotation scheme so that, once established, each subsequent backup finishes by deleting the oldest one? I'm concerned that if I only have a single backup, as currently configured, and it somehow that copy gets corrupted, I'll have nothing to fall back on. Possible? Hoping so.

**Comment by HoffmannTom** [comment]
Hello,
you can run a script after backup automatically (Post-backup cmd).
Example scripts are provided in the zip package (folder \sample-scripts).
Check the file "keep_n_backups.cmd". You can use it as a template and adjust it to your needs.

Greetings, 
Thomas

**Comment by bz12** [comment]
Brilliant! My son, father, grandfather, and I, all thank you!
