### ISSUE TITLE
can't make it work

### ISSUE THREAD

**Issue by MisjaS** [HoffmannTom/outlookbackupaddin#47]
hi, i am possibly missing the obvious but can't seem to make the addin work. i installed it (no errors, it shows in the "programs and features" list but not visible in outlook.
when i manually try to add the addin outlook tells me it is not a valid office addin:

![image](https://user-images.githubusercontent.com/37960451/70817358-b1686280-1dd1-11ea-98b9-226dfc219cfc.png)

i use windows 10 and outlook 365 version 1911 Click-to-Run
any suggestions are welcome

**Comment by HoffmannTom** [comment]
Hello,
could you please verify the following:
The installation folder "C:\Program Files (x86)\CodePlex\outlookbackupaddin" must contain the following files:
- BackupAddIn.dll
- BackupAddIn.dll.manifest
- BackupAddIn.vsto
- BackupExecutor.exe
- BackupExecutor.exe.config
- Microsoft.Office.Tools.Common.v4.0.Utilities.dll
- Microsoft.Office.Tools.dll
- Microsoft.Office.Tools.Outlook.v4.0.Utilities.dll
- Microsoft.Office.Tools.v4.0.Framework.dll

The add-in is registered via the registry for office 64 Bit at:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
There should be a key "LoadBehavior".

If you have office 32 Bit, the key is:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn

If this key doesnt exist, you can run cmd.exe in admin mode, change to the installation folder and register the add-in via: BackupExecutor.exe /register

Is the add-in listed in Outlook (File --> Options --> Add-Ins)?

Hope this helps to narrow down the issue.

Greetings, Thomas

**Comment by MisjaS** [comment]
Hello Tom,

Thanks a lot for the reply. I checked the folder and all files exist:

[cid:image001.png@01D5B5B9.C5455450]

Also checked registry and the key exists:
[cid:image002.png@01D5B5B9.C5455450]
But maybe some of the values are invalid?

The add-in is not available in the list on outlook:
[cid:image003.png@01D5B5B9.C5455450]

--
Vriendelijke groeten,

Misja Starink

**Comment by HoffmannTom** [comment]
Hello Misja,
unfortunately the attached pictures didn't survive the upload.

Can you try to register the add-in via command line (as described above)?
--> BackupExecutor.exe /register

If it doesnt work, you can drop a line via email.
Then the screenshots will also survive.

Greetings, Thomas

**Comment by MisjaS** [comment]
Hi Tom,
thanks, manually register worked i have the backup tab now visible in outlook.
thanks for the help.

i have a new question immediately (sorry):
i have two ost files in this outlook profile: one for an exchange account and one for an imap account but only the exchange account is visible in the add-in for backup. any suggestion how i could backup the imap account too?

<img width="344" alt="Annotation 2019-12-19 104155" src="https://user-images.githubusercontent.com/37960451/71162847-37f6c700-224c-11ea-9279-4c54fc3cb411.png">
<img width="432" alt="Annotation 2019-12-19 104155" src="https://user-images.githubusercontent.com/37960451/71162930-5f4d9400-224c-11ea-8404-a01792bd944f.png"
<img width="398" alt="Annotation 2019-12-19 104155" src="https://user-images.githubusercontent.com/37960451/71163069-a63b8980-224c-11ea-9b05-687ce7b629cf.png">

**Comment by HoffmannTom** [comment]
Hello Misja,
I am glad it worked, thanks for the reply.
Exchange and IMAP accounts are server-side managed accounts.
Why it is a bad idea to backup ost files is described here:
https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)
(Backup ost files will lead to a situation where you can't recover the mails as they are not readable after restoring the OS for example)

Possible options are to use POP instead of IMAP or create a rule in outlook which
copies mails to an extra PST-File.

Greetings, Thomas

**Comment by MisjaS** [comment]
Hi Tom,

Thanks for the link and the reg switch to enable ost support now both ost files are visible in the backup settings (strange that the exchange ost was already visible before setting this key).

I see your statement about backup of ost files not being totally useful as indeed you can only restore into the same profile on an existing laptop/pc but I disagree because of a recent experience:

My mobile phone somehow deleted my imap inbox (probably because of some in my pocket touch screen actions).

This was very scary as I had some important emails from the last months that still needed to be reacted on in the box. When I noticed it I went to my recycle bin on the phone (outlook app) and tried to move them all back to the inbox but outlook app crashed and after that the inbox and the recycle bin were both empty!

I sent an email to my provider and asked for a restore of my inbox. They are not as good as they used to be so it took them more then a week to respond end when they did the restore it appeared that they didn’t have more then a week of backup so the only result was all items from the last week now double in my inbox and the lost mail still lost.

It is a bit a long story but in this case a backup of the ost file would in my opinion really have helped me out so indeed as a general backup for a lost or crashed laptop the backup of an ost file is not very useful but also not needed as all mail will still be on the servers but in a case like above I feel it is very useful. I must say I am using email since it was invented and this is the first time this happened but having mail on my mobile and my mobile occasionally doing odd things makes it very well possible this will happen again.

As I access my email on numerous devices and sometimes even on webmail pop mail is no option for me.

Hope this explanation makes sense to you and is not to boring and thanks again for making it all work.

--
Vriendelijke groeten,

Misja Starink

**Comment by HoffmannTom** [comment]
Hello Misja,
I understand your use case and if you are aware of the limitations, you can use the ost backup.
I just dont want to claim that the backup of ost files is safe and let users believe in this.
Thats why the function is a bit hidden and not active per default.
(Your two ost files seem to have different internal mailbox types but there is no option to check this via Outlook)

I wish you a hopefully crash-free new year in advance,
Thomas
