### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by MadManLabs** [HoffmannTom/outlookbackupaddin#48]
Is the password to the keys mentioned in any of the docs? or maybe I am blind

**Comment by HoffmannTom** [comment]
Hello,
I am not sure what your question is about. There is no password within this add-in.
Which keys are you referring to?

Greetings, Thomas

**Comment by HoffmannTom** [comment]
Hello,
the issue will be closed within the next 2 weeks if no further information is added.
Greetings, Thomas

**Comment by HoffmannTom** [comment]
Closed due to inactivity
