### ISSUE TITLE
Blur screen with Hi Resolution displays

### ISSUE THREAD

**Issue by usb1284** [HoffmannTom/outlookbackupaddin#5]
![przechwytywanie](https://user-images.githubusercontent.com/30357985/28484227-811bfbee-6e71-11e7-8dd8-4428e8a7d7af.JPG)

while using HiRes monitors bakup screen as per image attached is blur
Can someone think to make such a small improvement?

**Comment by HoffmannTom** [comment]
Hello,
i can made a change regarding this topic but I cant test it. Is it possible to send you a new exe file with some adjustments regarding High DPI?

Regards,
Thomas

**Comment by usb1284** [comment]
Yes please do that

9 sie 2017 21:40 "HoffmannTom" <notifications@github.com> napisał(a):

**Comment by usb1284** [comment]
please let me know how to download that enhanced version.
Rob

**Comment by HoffmannTom** [comment]
Hello Rob,
a DPI aware version is available here: [https://ufile.io/eb0ip](https://ufile.io/eb0ip)
Please unpack and replace the old exe file with the new one.
Let me know if this did the trick.

Thanks!
Thomas

**Comment by usb1284** [comment]
Tom
yes it did the job thank you. Looks great now!

*Robert Stefaniak*


2017-08-10 19:47 GMT+02:00 HoffmannTom <notifications@github.com>:

**Comment by HoffmannTom** [comment]
Enhancement is pushed into development branch
