### ISSUE TITLE
Mit Jahreswechsel Fehlermeldung

### ISSUE THREAD

**Issue by MichaelC1806** [HoffmannTom/outlookbackupaddin#50]
Hallo Tom,
ich benutze Dein Addin schon seit vielen Jahren. Aktuell die Version 1.9.
Seit Beginn des Jahres 2020 wird die Sicherung nicht mehr durchgeführt.
Getting file lock...
starting copying...
Failed to copy file: Die Anforderung wird nicht untertützt
One or more errors occured. Please check the messages above and clos this window manually

Es gab keinerlei Veränderungen an Hard und Software
Office 365
Win10 prof
64-Bit

Hast Du irgendeine Idee was da los ist?

Viele grüße aus Hamburg, Germany
Michael

**Comment by HoffmannTom** [comment]
Hallo,
ist das Ziel ggf. FAT formatiert und die pst mittlerweile größer als 4 GB?
Bitte probiere mal ein anderes Ziel aus (z.B. anderes Verzeichnis auf der Platte)
Viele Grüße, Thomas

**Comment by MichaelC1806** [comment]
Ja, die Datei ist ca. 4,7 GB groß, allerdings schon seit einiger Zeit und bisher ohne Probleme. Die Datei wird im Netzwerk auf einem Server gesichert.
Deinem Rat folgend habe ich es heute auf meinem lokalen Laufwerk gesichert - ohne Probleme. Aber ich würde es natürlich weiterhin gerne auf dem Server sichern.
Viele Grüße
Michael

**Comment by Fran978** [comment]
Same problem here

**Comment by HoffmannTom** [comment]
Hello,
for consolidation reasons, this issue will be tracked with ticket https://github.com/HoffmannTom/outlookbackupaddin/issues/51
Please add any further information within this ticket.

Greetings, Thomas
