### ISSUE TITLE
Mit Jahreswechsel Fehlermeldung II / Failed to copy file

### ISSUE THREAD

**Issue by TWerkman** [HoffmannTom/outlookbackupaddin#51]
Heya,

danke für das tolle Addin :)
Seit Jahreswechsel habe nun auch ich mit folgendem Fehler zu kämpfen:

08:14:24 Getting file lock...
08:14:24 Starting copying...
08:14:24 Failed to copy file: Unzulässige Funktion
08:14:24 One or more errors occurred. Please check the messages above and close this window manually.

Ein paar Eckdaten:
Datei wird auf eine Netzwerkfreigabe gesichert (NTFS).
PST bereits 4,94GB groß
Win 10 und Office 2016 ProPlus (32bit)

...Das Sichern auf eine lokale Festplattenpartition funktioniert ohne Probleme.
Nochmals Danke und Vg

Tobi

**Comment by TWerkman** [comment]
Ergänzende Info:
PST wurde auch schon in mehrere PSTs aufgesplittet um Probleme mit der Dateigröße auszuschliessen. Dies führte leider nicht zum gewünschten Erfolg :(

**Comment by Fran978** [comment]
Same problem here, pst is 1.7Gb on ntfs, trying to copy on a network share Z:\
Worked fine since a week ago, I bet it's a windows 10 update that screwd up things

**Comment by TWerkman** [comment]
Update could be a good clue...
Last pst-backup i remember was on 13.12.2019...
On the same day 2 updates were installed (KB4533002) and (KB4530684).
I´ll try to uninstall these two, so i can find out, if one  is to blame for this issue

**Comment by TWerkman** [comment]
> 
> 
> Update could be a good clue...
> Last pst-backup i remember was on 13.12.2019...
> On the same day 2 updates were installed (KB4533002) and (KB4530684).
> I´ll try to uninstall these two, so i can find out, if one is to blame for this issue

Okay... this didn´t work :(

**Comment by Fran978** [comment]
Tom?

**Comment by tinzDROID** [comment]
Also have this issue when copying to a CIFS share with NTFS. Local drive destinations are fine.

**Comment by HoffmannTom** [comment]
Hello,
could you add some information about the target system?
Is it another Win10 computer or is it a NAS?
Which OS is running on the target machine?

Greetings, Thomas

**Comment by Fran978** [comment]
My target is a nas share, mapped to drive z: 
The nas is a Synology, brtfs filesystem on raid10 conf.
Origin is win10 x64
Last backup is on 18/12/2019

**Comment by tinzDROID** [comment]
My target is a Synology NAS with ext4 volumes shared over CIFS (SAMBA), there is 2.4tb available space on the NAS.
The source is a Windows 10 PC with NTFS.
I have tried with a mapped device and UNC (Previously while the backup was working, UNC was used)
I am able to manually copy the files over from the command line and from Explorer.
The PST files are between 800mb - 3.5gb.

**Comment by HoffmannTom** [comment]
Hello,
it seems the problem narrows down to the combination with a Synology NAS.
I tried with Win10 as a target PC via network without any problems.
Can you provide the English error message of the line ... Failed to copy file: ?

I will try to search online if there are any compatibility issues with the NAS.
As a workaround you could use the Post-Backup-cmd and run a little bat-file to copy the pst to the NAS.

Greetings, Thomas

**Comment by HoffmannTom** [comment]
Could you try to enable SMB 3 as described at:
https://community.synology.com/enu/forum/7/post/120393 ?

**Comment by TWerkman** [comment]
Situation here:
Fileserver 2008R2 (we´re migrating this month...really!) with following disk/drives:
C:\ - RAID1 on Fileserver
E:\ - RAID5 on Fileserver (contains the share with the pst-backup-files)
F:\ - RAID5 attached via iSCSI (Synology-NAS) (not containing the share with the pst-backup-files)

On the W10-Client i checked the smb-dialect (powershell: get-smbconnection) and saw that the connection to the server for the pst-backup uses smb-dialect 2.1. 

Fortunatly we got another server (Server 2016) with shares using smb 3.1.1... I´ll try to set this server as target for the backuptool.

**Comment by TWerkman** [comment]
> 
> 
> Situation here:
> Fileserver 2008R2 (we´re migrating this month...really!) with following disk/drives:
> C:\ - RAID1 on Fileserver
> E:\ - RAID5 on Fileserver (contains the share with the pst-backup-files)
> F:\ - RAID5 attached via iSCSI (Synology-NAS) (not containing the share with the pst-backup-files)
> 
> On the W10-Client i checked the smb-dialect (powershell: get-smbconnection) and saw that the connection to the server for the pst-backup uses smb-dialect 2.1.
> 
> Fortunatly we got another server (Server 2016) with shares using smb 3.1.1... I´ll try to set this server as target for the backuptool.

Nope, the second time i tried to backup the pst-file to the server (the one with smb3.1.1) gives the same error message as in the first comment :(. 
it´s weird because i can backup the pst-file if the backupfolder is empty... if i try to overwrite the backupfile it doesnt work...

**Comment by HoffmannTom** [comment]
Hello,
I also tried with Win2008R2. Using a normal network share worked, even with overwriting.
Can anyone send the english error message which is shown in the log output?
Greetings, Thomas

**Comment by HoffmannTom** [comment]
Can somebody try to monitor the copy process Procmon: with https://docs.microsoft.com/en-us/sysinternals/downloads/procmon ?
Maybe this shows some permission issues or other hints.

**Comment by TWerkman** [comment]
I never used procmon, so i hope this was the correct way to do so...
I set a filter (processname = backupexecutor.exe) cleared the results started outlook and closed it again to initiate the backup-process... procmon showed a bunch of entries... i could upload this enormous file i you want to... otherwise after looking through these entries i saw this event (maybe it helps?):

<event>
<ProcessIndex>1770</ProcessIndex>
<Time_of_Day>11:20:58,9825554</Time_of_Day>
<Process_Name>BackupExecutor.exe</Process_Name>
<PID>63556</PID>
<Operation>CreateFile</Operation>
<Path>\\fiw-fs2\PST-Backup\Twerkman\Werkman.pst</Path>
<Result>INVALID DEVICE REQUEST</Result>
<Detail>Desired Access: Generic Read/Write, Delete, Write DAC, Disposition: OverwriteIf, Options: Sequential Access, Non-Directory File, Attributes: ANCI, ShareMode: None, AllocationSize: 1.010.361.344</Detail>
</event>

**Comment by Fran978** [comment]
[Logfile.zip](https://github.com/HoffmannTom/outlookbackupaddin/files/4076412/Logfile.zip)

**Comment by HoffmannTom** [comment]
@Fran978: the logfile contains the same error message as TWerkman:
INVALID DEVICE REQUEST
It seems that some protocol functions are not supported by the target. Maybe an SMB protocol issue.

**Comment by TWerkman** [comment]
so we can assume that there is no "invalid device message" in a working "pst-backup-scenario"-logfile?
can you confirm this?

**Comment by TWerkman** [comment]
I wiresharked the backup-process and got this message of an unknown ioctl request...
Maybe someone with more wireshark experience is here and knows the meaning of this.
![Unbenannt](https://user-images.githubusercontent.com/59597749/72615888-fe41da80-3935-11ea-9b8e-a38661993bac.jpg)

**Comment by TWerkman** [comment]
Here a snippet with some more information to the ioctl-request... says also unknown device...

![grafik](https://user-images.githubusercontent.com/59597749/72618158-ce490600-393a-11ea-8002-80e5a74dce0c.png)

**Comment by HoffmannTom** [comment]
Hello,
within a working backup there is no message like "INVALID DEVICE REQUEST":
![image](https://user-images.githubusercontent.com/27145868/72627039-11f83b80-394c-11ea-9107-2821f8e8ec70.png)

**Comment by HoffmannTom** [comment]
Hello,
could you try to (temporary) disable and AV software on client + server?
Is there any relevant message in the event log on server or client side which is related to this message?
Up to now I couldn't reproduce the error. Neither with Win10 nor with Win2008R2 on server side.
Greetings, Thomas

**Comment by TWerkman** [comment]
Heya,

i‘ll try it on monday. i think it could be interesting which av software is used by the other users.
We use kaspersky internet security and kaspersky total security on the w10 clients and server runs with sophos antivirus. another question... do the other persons use dfs on their fileserver?

**Comment by HoffmannTom** [comment]
Hello,
we use GData AV on server and client side.
I will be back in February. I hope you can narrow down under which circumstances the problem
shows up.
Greetings, Thomas

**Comment by tinzDROID** [comment]
> Heya,
> 
> i‘ll try it on monday. i think it could be interesting which av software is used by the other users.
> We use kaspersky internet security and kaspersky total security on the w10 clients and server runs with sophos antivirus. another question... do the other persons use dfs on their fileserver?

We're using Kaspersky KTS on the clients and Synology's Antivirus tool which I believe uses the ClamAV engine. No dfs.

**Comment by TWerkman** [comment]
Great news!

It seems to be, that kaspersky is the problem for us...
I accidental discovered this as i was solving some issues with the client firewall and a the hyper-v manager (but this is another story)...
anyways, with kaspersky are three modes:
- protection running
- protection stopped
- closed

as the protection runs, it´s not possible to rewrite the pst-file. same issue when protection is stopped (but kaspersky still running as process)
only if kaspersky-process is killed it´s possible to re-do the pst-backup!

maybe i´ll find a solution to make this work with kaspersky again.

**Comment by TWerkman** [comment]
ok it´s just a workaround by disabling the monitoring of the process-activity of the pst-backup.exe, but maybe someone has a better idea later...

1. Open Kaspersky Settings
2. Open Protection
3. Open Programcontrol
4. Open Manage Programs
5. rightklick and select add program to group
6. select the backupexecutor.exe (C:\Program Files (x86)\CodePlex\outlookbackupaddin\BackupExecutor.exe)
7. search the backup executor entry, right click it and select details and rules
8. navigate to exceptions
9. tick do not monitor programactivity
10. save and close

---- As you see it´s just a workaround by disabling some security settings, so keep that in mind. Also have in mind that this manual is valid for the kaspersky-internet-security-suite. some steps in total security could be different. as i have the german version of kaspersky there might be translation differences to the steps i´ve written, so sorry for that! maybe someone with a better english might help here

**Comment by tinzDROID** [comment]
I've tried TWerkman's workaround and it's working for me, using Total Security, only slight difference from above:

1. Open Kaspersky Settings
2. Open Protection
3. Open Application Control
4. Open Manage Applications
5. Search for the BackupExecutor application in the list (in mine it was under Low Restricted> Codeplex) but find us using the search box.
6. Right click and select Details And Rules
7. Click on the Exclusions tab
8. Tick do not monitor Application Activity
9. Save

**Comment by Fran978** [comment]
I can confirm it works thanks to TWerkman

**Comment by MichaelC1806** [comment]
Auch ich kann bestätigen, dass es Dank der Hilfe und Vorgehensweise von @TWerkman reibungslos funktioniert. Vielen Dank! 👍

**Comment by HoffmannTom** [comment]
I added this information to the wiki page to keep this information permanently:
https://github.com/HoffmannTom/outlookbackupaddin/wiki
Thanks for your input and participation to solve this issue.
