### ISSUE TITLE
can't find setup.exe

### ISSUE THREAD

**Issue by paulgdavitt** [HoffmannTom/outlookbackupaddin#54]
Downloaded the zip file (twice), unzipped but I don't see the setup.exe file.  The readme file says to run setup.exe but I don't see it.  I have hidden files turned on in Windows file explorer.  Am I crazed?

Thanks, Paul G.

**Comment by HoffmannTom** [comment]
Hello Paul,
please download the release at https://github.com/HoffmannTom/outlookbackupaddin/releases
and start the msi-File.
Greetings, Thomas

**Comment by paulgdavitt** [comment]
Thanks, Thomas, if worked perfect!  Appreciate your work, I’m very frustrated the fine folks at Microsoft left this out of the new version.  Now I can update all the machines here.

 

 

Thanks, Paul G. Davitt

 

 

 

Paul G. Davitt

Operations Manager

Cal-Ore Produce

(541) 363-0101

(541) 591-2260 (cell)
