### ISSUE TITLE
There is no .pst to Backup

### ISSUE THREAD

**Issue by On3Try** [HoffmannTom/outlookbackupaddin#55]
Ive got a problem: after i istalled the addin, i checked the setttings but theres everything empty. 
Can someone tell me how to fix it? Thanks a lot!
![Empty](https://user-images.githubusercontent.com/61736440/75768259-48dfb080-5d44-11ea-957f-91fdafe60408.JPG)

**Comment by HoffmannTom** [comment]
Hello,
please check out the wiki page:
https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)
Maybe you find the answer to this topic.

Greetings, Thomas

**Comment by On3Try** [comment]
> Hello,
> please check out the wiki page:
> https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)
> Maybe you find the answer to this topic.
> 
> Greetings, Thomas

Hello Thomas,

that doenst worked. I checked the type of file it ist already .pst i also checked the registry and added the information from the wiki. Any Idea? :)

**Comment by On3Try** [comment]
I changed now to a new PC but still the same. There is no file to backup. I dont know where the problem is. Any new Ideas?

**Comment by HoffmannTom** [comment]
Hello,
could you post a screenshot of outlook --> Files --> Account settings --> Tab "Data files" ?
Maybe this might shed light onto this case.
Thanks! Thomas

**Comment by HoffmannTom** [comment]
Hello,
do you have any updates on this topic?
Greetings, Thomas

**Comment by HoffmannTom** [comment]
I am closing this issue due to lack of information and response.
