### ISSUE TITLE
Plugin not visible

### ISSUE THREAD

**Issue by PDN2020** [HoffmannTom/outlookbackupaddin#56]
Installed your tool on 3 different PCs
Windows 10
on one the Addon is visible, on 2 not. Can you give me a hint what to do?
Outlook professional plus 2019
Thanks

**Comment by PDN2020** [comment]
found the trick with BackupExecutor.exe /register in an old issue
works fine now

**Comment by thomass4t** [comment]
I am glad it worked out :)
