### ISSUE TITLE
Setting Interval a Number Between 0 and 1 Days Doesn't Work 

### ISSUE THREAD

**Issue by viking2** [HoffmannTom/outlookbackupaddin#57]
Great Addin!

I would like to backup when I close Outlook once every day (in the evening) so I set the Interval=1 day.  I may close my Outlook at 10 PM one day and then 9:30 PM the next day. In this case, the backup does not start because exactly 1 day (24 hours) hasn't passed yet. 

I tried to set the backup to some number less than 1 day, e.g. 0.75=18 hrs to solve this issue, but that didn't work. Only 0 or 1 is allowed :-(.

Could you possible modify the addin to set the interval in hours (or fractional days) so that it doesn't matter when exactly in the evening Outlook is closed?

TIA!

**Comment by HoffmannTom** [comment]
Hello TIA,
in the next version, you will have the possibility to set not only days but also hours.
(for now this settings has to be done within the registry HKCU\SOFTWARE\CodePlex\BackupAddIn\Settings)
You can set the days to 0 and the hours to e.g. 12.

Greetings,
Thomas

**Comment by viking2** [comment]
Hello Tom,

I looked in the registry and assume that I need to modify the Interval? It is now set to 1 (Hexadecimal).
How do I change it to 12 hours?

Thanks,
Erik

p.s. TIA = Thanks in advance

**Comment by HoffmannTom** [comment]
Hello Erik,
there is a new registry key "IntervalHours" available in the new version.
As it is not released yet, you would need to compile it from source or you can drop me an email
(see my profile to get my contact email). Then I can send you a compiled version.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Feature was implemented.
