### ISSUE TITLE
Is There Some Way of Pausing or Stopping a Backup?

### ISSUE THREAD

**Issue by viking2** [HoffmannTom/outlookbackupaddin#58]
Is There Some Way of Pausing or Stopping a Backup?
If not, could that feature be added? Please...?
TIA!

**Comment by HoffmannTom** [comment]
Hello,
interrupting the backup is currently disabled. This would cause a broken backup.
The old backup would be partially overwritten and the new one is not finished / broken.
Thats why closing the program during backup is currently disabled.
Greetings, Thomas

**Comment by viking2** [comment]
My "Solution" has been to kill it in task manager. I realize that it causes a broken backup, but it will be overwritten in the next uninterrupted backup.

**Comment by HoffmannTom** [comment]
Hello,
I think there is a feature which already meets your needs.
You can set a countdown within the settings dialog.
If you set it to e.g. 10 seconds, you have this time left to cancel the backup.
After the countdown, the program can't be cancelled any more. But this gives you time to decide
if you have enough time for proceeding with the backup.
I hope this helps
Greetings, Thomas

**Comment by viking2** [comment]
I tried the countdown. 
However, during the countdown there is no button to cancel the backup. Do I need to bring up Task Manager and kill it from there during the countdown? 
I didn't have time during a 10 sec countdown to do this. I prefer to not set it to too much longer.
It would be great to have a cancel button during the countdown. 
Thanks in advance!

p.s. Did you see my other issue (#57) regarding being able to set the interval < 24 hrs?

**Comment by HoffmannTom** [comment]
Hello,
during the countdown you can close the program by clicking on the right top corner at [x]
This will end the backup program without need for task manager.
I saw the other ticket and will check which solution might be adequate.

Greetings, Thomas

**Comment by viking2** [comment]
That works !
Thanks, Erik
