### ISSUE TITLE
the back up window does not close at the and of its work

### ISSUE THREAD

**Issue by usb1284** [HoffmannTom/outlookbackupaddin#6]
the back up window does not close at the and of its work. Is there any solution for that?

**Comment by HoffmannTom** [comment]
Hello,
the backup window closes automatically when everything went fine.
If it stays open, it usually means that an error happened. Please check the output window for any errors.
If you can't fine anything, please post a screenshot of the last screen which is visible.

Thanks!
Thomas

**Comment by usb1284** [comment]
Reinstal helpdesk :-)

9 sie 2017 15:59 "HoffmannTom" <notifications@github.com> napisał(a):

**Comment by HoffmannTom** [comment]
Hello,
I interpret this as this ticket can be closed :)
