### ISSUE TITLE
Can't run with multiple user accounts

### ISSUE THREAD

**Issue by Scally-H** [HoffmannTom/outlookbackupaddin#60]
Thank you for this backup solution! My PC has 3 user accounts, all using one office 2019 installation. But the script fails to run (times out) if Outlook is still open in one of the other user accounts, even though they are not using the same folder/pst file locations. Maybe this would work if its search for the Outlook process was constrained to the current user space? Thanks!

**Comment by HoffmannTom** [comment]
Hello,
do you use windows server or terminal server?
Usually Microsoft only allows the usage of the office license to one main user.
Otherwise you need an SA from Microsoft to cover several parallel users on a terminal server environment.
Greetings, Thomas

**Comment by Scally-H** [comment]
I just have win10 pro, and installed office via an admin account, but also have 2 normal user accounts on the same PC. Office just lives on the C: drive visible to both accounts and each can run all the office apps. Each user has a folder under C:\users . So each user has its own set of apps running. I believe this is a feature of Win10 Pro (and was true for Win7 pro too).

If only 1 user is using Outlook, on close it runs the backup. But if another logged-in user is also running Outlook (with its own pst file and email account), the script fails as it sees Outlook still running. Hope this helps!

**Comment by HoffmannTom** [comment]
Hello Scally,
so you are using Win10 not parallel but the offline-users are stilled logged on, right?
So when you are using the PC, the other persons are away but still logged on (?)
Checking the process and the username should work with some adjustments on the plugin.
Greetings, Thomas

**Comment by Scally-H** [comment]
Yes indeed. Only one user can physically use the PC at any one time, but others remain logged in, so Outlook process for them is still running and collecting emails every so often. Great if you can tweak your plugin to match with the user's account/processes. It already shows the correct pst path (i.e. distinct for each user).
Kind regards.

**Comment by HoffmannTom** [comment]
Hello Scally,
the development branch is updated.
You can either compile the development-branch or just send me an email via the contact form.
Then I will send you a compiled version.
Greetings, Thomas
