### ISSUE TITLE
Can You Help Please

### ISSUE THREAD

**Issue by MarketerStephen** [HoffmannTom/outlookbackupaddin#64]
Hi,
Thanks for the plugin (I am still using Outlook 2013 and your backup plugin after all these years!) - I just had to reinstall Outlook but now I cannot figure out how to restore the backups I made and saved to Dropbox.
I created the same email accounts and then in the data file section I selected the backups in dropbox (i think this was a mistake as I now get an error in dropbox saying "cant sync - file in use." 
I also get an error when I shut outlookk down saying backup failed)  

13:39:13 Can't copy file on it's own, skipping: C:\Users\MarketerStephen\Dropbox\stephen@stephenstrydom.co.za.pst
13:39:13 One or more errors occurred. Please check the messages above and close this window manually.

Is there a guide on how to fix this please?

Much appreciated.
Regards,,,
Stephen Strydom

**Comment by HoffmannTom** [comment]
Hello Stephen,
it seems you have two problems.
1) Please restore the pst file from dropbox to any local folder. You should be able to access the mails via
    Outlook --> File --> Open & Export --> Open Outlook Data File (maybe slightly different in Office 2013)
2) The message indicates that the configured backup path is the same path where the current pst file is located.
     The backup addin will copy the pst to the configured destination directory. This should be different to the source directory.

I hope this information helps.

Greetings, Thomas

**Comment by MarketerStephen** [comment]
Hi Thomas,
Thanks so much for taking the time to assist me.
If I understand correctly you are saying I must copy the backup .pst file that is in dropbox and place it in the local (outlook files) folder. 
Once this is done, do I leave the file in dropbox and start backing up as usual or do I delete the exisitng pst file that is in presently dropbox after I copied tt to my local folder?

Thanks again,
Stephen Strydom

**Comment by HoffmannTom** [comment]
Hello Stephen,
if the restore of the pst file was successful (please verify in outlook), you dont need to keep it in dropbox any more.
You can continue the normal backup process after you have verified that you have your emails back.

Greetings, Thomas

**Comment by MarketerStephen** [comment]
Thank you very much Thomas, i got it sorted 
Thanks a million for your help!
Have  a great day.
Regards,
Stephen Strydom
