### ISSUE TITLE
Settings dialog shows no entries II

### ISSUE THREAD

**Issue by NiceCommunicativeAndSerious** [HoffmannTom/outlookbackupaddin#66]
Hello,

I have the issue that i have no postentries o select for saving.
I want to save .PST datas, the dialog window looks like thise:
![image](https://user-images.githubusercontent.com/92846758/138045414-a8d32126-6401-4ae4-9441-ca41f0ea5984.png)
i have the problem on Office (Outlook) 2016 as well as Office (Outlook) 2019.

Thank you for your help
with best regards:)

**Comment by NiceCommunicativeAndSerious** [comment]
Hello,
i've dobble checked it. its pst files.
the mailboxes are stored with the suffix .pst

greetings

**Comment by HoffmannTom** [comment]
Hello,
the plugin filters files, which dont have a path or when the type is not supported.
Could you check the tab with the data files whether there is a valid path?
![image](https://user-images.githubusercontent.com/27145868/138087808-d5e2d2c1-3034-417f-954a-37900dbafd96.png)

**Comment by NiceCommunicativeAndSerious** [comment]
Hello,
the Path is valid, its saved in a of C:/Users

**Comment by NiceCommunicativeAndSerious** [comment]
Hello,

did you got my email?
I used the title of this thread as reference.

Greetings

**Comment by NiceCommunicativeAndSerious** [comment]
Hello,

Thank you for your help. with the Debugging file the Problem seems solved. now it is running.
