### ISSUE TITLE
If errors occur, there is no persistent indication

### ISSUE THREAD

**Issue by doundis** [HoffmannTom/outlookbackupaddin#69]
Sometimes errors prevent the .pst files backup, e.g. files being locked, and are displayed in the backup window.
But the is closed short after, as if the backup was successful, leaving the user with the impression everything went fine.
So, the problem never reaches the IT to be solved and in case the backup needs to be retrieved, it's outdated.

A way to help this issue, may be to leave the backup window open after any errors occur.
Maybe would help too having a simple line like this at the end:  ----BACKUP FAILURE---

**Comment by HoffmannTom** [comment]
Hello,
in the current version, the window stays open whenever an error occurs.
The last shown message is e.g.
"14:42:53 One or more errors occurred. Please check the messages above and close this window manually."

Thus your requested feature should already be implemented.
1) Can you check, whether you have the current version?
2) What do the messages show?

Greetings,
Thomas

**Comment by doundis** [comment]
You are right Thomas, it has an older version.
