### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by GheeLipOng** [HoffmannTom/outlookbackupaddin#7]
Greetings,

Wondering if there is a way to save messages to a file as it runs the backup. Goes by too fast to read.
Windows 10 - Outlook 2016

Thanks.

**Comment by HoffmannTom** [comment]
Hello,
if the window closes automatically it means everything was ok and no errors happened.
If you want to see the whole message for one time, you can run BackupExecutor from command
prompt. This will leave the message within the command window. Just add parameter /backupnow to run backup.
Is this sufficient in your case?
Greetings,
Thomas

**Comment by GheeLipOng** [comment]
Thanks Thomas,

However I have a question.  Below is the message I received and wondering
what it means when it say "File is Locked".

The same message for each of the profiles.

Check whether outlooks is still running ...
No outlook process found
Ensure only one instance running ...
Check whether target directory exists...
Summing up file sizes ...
Total bytes calculated...
Evaluate destination path...
copy D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost to D:\OneDrive - GHEE LIP ONG\Outlook
Backup\Technical.Management@GheeLipOng.com - Ghee Lip's Profile.ost
Getting file lock...
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
File is locked: D:\Outlook\Technical.Management@GheeLipOng.com - Ghee Lip's
Profile.ost
Starting copying...


The programs does close automatically at the end of the run.
Please advise.

Thanks again.
*Ghee Lip Ong*
Voice | Message: 917.723.3551
GheeLip@GheeLipOng.com
http://www.GheeLipOng.com

**Comment by HoffmannTom** [comment]
Hello,
it indicates that the ost-file is locked by a program. Copying might fail therefore.
If you want to know which program locks your ost-file, you can use:
https://docs.microsoft.com/de-de/sysinternals/downloads/handle
to figure it out.
Please note that backing up ost files is not a good idea. Further information is
available at [https://outlookbackupaddin.codeplex.com/wikipage?title=Files%20are%20not%20shown%20for%20backup](https://outlookbackupaddin.codeplex.com/wikipage?title=Files%20are%20not%20shown%20for%20backup)

Greetings,
Thomas

**Comment by GheeLipOng** [comment]
Thanks Thomas.
