### ISSUE TITLE
Not works for ost file type ?

### ISSUE THREAD

**Issue by an0nimo** [HoffmannTom/outlookbackupaddin#70]
When outlook 2019 is set for IMAP mode, the data file is **OST** type but in POP3 mode the data file is **PST** type. So, **outlookbackupaddin** only works for **PST** file type (POP3) and not for **OST** file type (IMAP). **Correct ?**
Because I use outlook for IMAP mode of accounts and all OST data files can't be found by outlookbackupaddin.

**Comment by HoffmannTom** [comment]
Hello,
there is a wiki page describing the situation with OST-files:
https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)

In short: backup of OST-files  can be activated but it's not very useful not advised.

Greetings, Thomas

**Comment by an0nimo** [comment]
Thank you so much for your quick support.
Well, the IMAP mode to work is better and more easy because the local changes will happen on the server too.
The backup not need to be in OST file type because we need a simple backup, so, the OST file can be converted in PST file as the final backup process. If I need access the backup to recover some message, simply the PST backup file can be open in outlook.
I've tried export the email IMAP accounts to PST file but didn't work.
So, to around the issue, in outlook I created a new data PST file called "backup", copied the folders email IMAP account and pasted in "backup" account manually. I have to do this manually one time on week at least to keep backup updated.
I also will do what you said in your prevoius message.
Have a nice day.

**Comment by an0nimo** [comment]
> Hello, there is a wiki page describing the situation with OST-files: https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)
> 
> In short: backup of OST-files can be activated but it's not very useful nor advised.
> 
> Greetings, Thomas

I activated the backup OST file within windows registry and it worked very nice.
Thank you again.
