### ISSUE TITLE
Probleme mit der Einstellung von Outlook-Backup

### ISSUE THREAD

**Issue by SusanneTossing** [HoffmannTom/outlookbackupaddin#71]
Hallo,
ich habe das Programm Outlook-Backup gefunden zum automatischen Sichern meines Outlook.
Ich habe das Programm heruntergeladen, es erscheint auch als Add-In oben in der Leiste als Backup . Ich bin auf Einstellungen gegangen , alles sah gut aus. Doch ich komme nicht zum Feld  ganz oben "Outlook-Dateien" um dort die Dateien (pst-Dateien) anzugeben dich gesichert werden sollen - ich kann da nichts hinschreiben/angeben. 
Und so kommt dann beim Schließen von Outlook die Fehlermeldung dass nichts gesichert werden kann, da keine Datei angegeben ist.

Können Sie mir bitte helfen, denn ich suche schon lange ein Programm für Outlook zur automatischen Sicherung!

Über eine Rückmeldung wäre ich sehr dankbar.

Grüße
Susanne Tossing

**Comment by HoffmannTom** [comment]
Hallo,
ich bin mir nicht sicher, was "nicht hinkommen" genau bedeutet.
Werden pst-Files angezeigt? Sind sie außerhalb des sichtbaren Bereichs?
Wurde die Windows-Schriftart oder das Design vergrößert, sodass das Layout des Fensters kaputt ist?
Bei Bedarf einfach einen Screenshot an die im Profil angegebene Adresse senden.
Viele Grüße, Thomas

**Comment by manfred-mueller** [comment]
Hallo,

zuerst Glückwunsch zu diesem Addin!

Ich habe das gleiche Problem wie Susanne Tossing, dass keine .pst-Dateien angezeigt werden oder ausgewählt werden können.

Nachfolgend 2 Screenshots der Einstellkungen und Fehlermeldung.

![grafik](https://user-images.githubusercontent.com/65389254/167093314-0b5ae986-acca-4bd3-a9d0-afc2d50d3d38.png)

![grafik](https://user-images.githubusercontent.com/65389254/167093399-812593d3-a721-4199-a2e6-583084d25d00.png)

Danke für outlookbackupaddin!

Gruß,

Manfred

**Comment by manfred-mueller** [comment]
Hallo Thomas,

vergiss bitte mein oberes posting: Ich benutze imap, habe also gar keine pst-Dateien...

**Comment by HoffmannTom** [comment]
@SusanneTossing 
Handelt es sich bei Dir auch um IMAP-Postfächer?
Oder handelt es sich um den gleichen Fall?
Kann das Ticket geschlossen werden?
Gruß, Thomas

**Comment by HoffmannTom** [comment]
Ticket wird geschlossen mangels Feedback.
