### ISSUE TITLE
IMPROVEMENT : Allow to define a backup location for each pst

### ISSUE THREAD

**Issue by OteJlo** [HoffmannTom/outlookbackupaddin#73]
Hello,

I would like to know if it would be possible to set up a backup location for each of my PSTs. I would like to be able to backup each of my PSTs, but not to the same location.

Is there a way to do this with your addin in a simple way?

Thanks in advance !

**Comment by HoffmannTom** [comment]
Hello,
I am aware that there are many different individual need and requests.
Therefore you can use the "post-backup cmd" to add individual scripts.
Examples are provided in the release file.

Greetings, Thomas

**Comment by OteJlo** [comment]
Thanks for the quick answer!

The problem is at the level of the place, if I understood well it will make the copy of all the pst that I want to save, that in the same place, then with a script I should specify the place where it is pst to move them one by one?

**Comment by HoffmannTom** [comment]
Hello,
it works a bit differently. The backup will be done as usual to the configured folder.
Your script has to iterate the files in the destination folder and move the pst-files to the desired location.
You can check the sample script which adds a date to the filename. Instead of renaming, you would have to 
move the file to the desired destination folder.

**Comment by HoffmannTom** [comment]
Hello,
did you achieve the desired result with the script?
Greetings, 
Thomas

**Comment by OteJlo** [comment]
Hello,

No, because the goal is to implement your application on each user station of our company.

The difficulty does not lie in the deployment or other, it is the fact of the blow to be able to make so that each user can save in only one copy each file in the place which is intended, because our users make backups of PST by business in the folder of the business, and for a lambda user a script it is not all easy.

But we are working on a post-backup solution where users could configure on an interface each file in a location and once configured create the script you are talking about that runs after the backup.

Thanks for your help!

**Comment by HoffmannTom** [comment]
Hello,
I am not quite sure about the mentioned issue.
So you have different departments with multiple users and every user shall get its own target folder. Is that right?
You can also use environment variables within the path, prefix and suffix, if this helps.

Greetings, Thomas

**Comment by OteJlo** [comment]
Hello,

MMm no that would not solve the problem, because each user has several PSTs, and each PST must be saved in a specific location on our network. (these are PSTs linked to construction sites).

And each user works on different sites.

Thanks for your help!

**Comment by OteJlo** [comment]
Hey,

So there's nothing you can do to make it work?

**Comment by HoffmannTom** [comment]
Hello,
using the "post-backup cmd" is my suggestion. You can use some if-statements to separate the pst files.
Furthermore you can use env-variables.
If there is a specific problem with writing a batch-files you can drop a line.
You didn't mention any specific problem regarding the batch-files solution or I didn't get the issue.
Greetings, Thomas

**Comment by OteJlo** [comment]
The problem with using the "post-backup cmd" function is that it runs after the PST files are copied.

So after copying the PSTs to a location X you would have to additionally do a move of the PSTs to each appropriate folder.

And depending on the throughput of some of our servers, the space left on some user workstations, this is not possible.

Can't you add an option to your add-in to separate the backup destination folder for each PST?

**Comment by HoffmannTom** [comment]
If all the pst-files are on the same server, moving the files between folders doesnt need any extra space.
Only the file descriptor is moved, not the file data itself.

**Comment by OteJlo** [comment]
it doesn't go on the same server, we have many servers.
