### ISSUE TITLE
BACKUP-Addin wird nicht angezeigt

### ISSUE THREAD

**Issue by myssv** [HoffmannTom/outlookbackupaddin#74]
Ich habe gestern das Tool deinstalliert und wollte es heute wieder installieren.
Die eigentliche Installation läuft durch, doch BACKUP wird mir nicht angezeigt.
Auch bei den Add-Ins ist es nicht zu finden.
![grafik](https://user-images.githubusercontent.com/65643813/171903470-97b44ced-9022-408a-89ad-28012c966a9e.png)
Was kann ich tun?
Vielen Dank schon mal!
Volker

**Comment by HoffmannTom** [comment]
Hallo!
Bitte mal die manuelle Installation probieren: 
Vielleicht genügt es Schritt 3 auszuführen und das Addin neu zu registrieren:
BackupExecutor.exe /register

**Comment by myssv** [comment]
Das hat leider nicht geholfen. 

![grafik](https://user-images.githubusercontent.com/65643813/171920292-983d2533-baf0-4ebb-bbee-a45e53e3373b.png)

Keine Änderung am Zustand.

![grafik](https://user-images.githubusercontent.com/65643813/171920328-75cb62d6-cca6-433b-85f2-f90aa4a75186.png)

**Comment by myssv** [comment]
Ach so:
Outlook 365 unter Windows 11
Wie gesagt, Bis gestern ist es super gelaufen, dann dachte ich, ich brauche es nicht mehr ...

**Comment by HoffmannTom** [comment]
Hallo,
haben Sie aktuell Outlook 32 Bit oder 64 Bit installiert?
Falls die Bittigkeit gewechselt wurde, können Registry-Reste die Installation behindern.
Für 64 Bit wird das Addin unter: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
registriert.
Für 32 Bit unter: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
Hier muss es einen Eintrag "LoadBehavior" geben mit dem Wert 3.

Evtl. hat Outlook das Addin auch deaktiviert. Hierzu können Sie in der Registry nach "Codeplex.BackupAddIn" suchen, ob es irgendwo als deaktiviert aufgeführt wird.
Manchmal zeigt es Outlook auch an, siehe z.B. https://help.senditsecure.com/article/88-legacy-enable-outlook-addin

**Comment by myssv** [comment]
Moin,

64 Bit:
![grafik](https://user-images.githubusercontent.com/65643813/171992667-452f3629-09ef-4351-ad53-6de582047a21.png)

Daran hat sich auch nichts geändert.

Den Eintrag gibt es:

![grafik](https://user-images.githubusercontent.com/65643813/171992760-77427cbe-ef45-4cbf-9f6f-bd8c706894a1.png)

Bei den Add-Ins steht aber nichts:

![grafik](https://user-images.githubusercontent.com/65643813/171992798-842e628a-f49f-467b-8e9e-d319104b25a4.png)

![grafik](https://user-images.githubusercontent.com/65643813/171992804-b6ffa18a-62ce-4e30-bf8a-18ee4962fb0f.png)

Ich habe nach der Deinstallation den CalDavSyncronizer installiert. Kann der das Backup Add.In irgendwie blockieren?

**Comment by myssv** [comment]
![grafik](https://user-images.githubusercontent.com/65643813/171993453-e573e279-108e-4497-b03e-2f418f8d31c0.png)

Der Eintrag bei "Manifest" sieht in meinen Augen komisch aus.

Die Dateien die es in dem Verzeichnis gibt sin dfolgende:

![grafik](https://user-images.githubusercontent.com/65643813/171993485-1f36fa66-7d53-4d02-8cf7-e2f687966f73.png)

**Comment by HoffmannTom** [comment]
Hallo,
der Registry-Zweig sieht soweit ok aus. 
Das mit | angehängte VSTO ist soweit ok und ist von Microsoft dokumentiert:
[https://docs.microsoft.com/de-de/visualstudio/vsto/registry-entries-for-vsto-add-ins?view=vs-2022](https://docs.microsoft.com/de-de/visualstudio/vsto/registry-entries-for-vsto-add-ins?view=vs-2022)
Der CalDavSyncronizer sollte keine Probleme machen.

Die einzigen zwei Optionen, die mir noch einfallen:
1) Registry nach Codeplex.BackupAddIn durchsuchen, ob es irgendwo als disabled aufgeführt wird
2) Gucken, wo CalDavSyncronizer sich in der Registry verewigt hat. Das Addin scheint ja geladen zu werden.
    (evtl. unter HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Outlook\Addins\ )

Was mir noch auffällt:
1) Soft XPansion scheint ja direkt unterhalb in der Registry eingetragen zu sein, das wird ja in Outlook angezeigt.
2) Das obige Dos-Fenster zeigt an "detected office 32 Bit "

**Comment by HoffmannTom** [comment]
Nachtrag:
Das msi kann über die DOS-Konsole mit aktiviertem Logging installiert werden:
msiexec.exe /i OutlookBackupAddIn.msi /l*v! install.log

Im Logfile ist erkennbar, woher die Meldung kommt, dass es angeblich 32 Bit ist (Suche im log nach "CheckOfficeBits")
Evtl. liegt noch irgendwo eine alte outlook.exe rum oder ein verwaister Registry-Eintrag.

**Comment by myssv** [comment]
![grafik](https://user-images.githubusercontent.com/65643813/171994723-1843ca3b-f32c-40ee-b179-51e891152860.png)

**Comment by myssv** [comment]
Möchtest Du evtl. Remote auf meinen Rechner kommen?

**Comment by myssv** [comment]
Bezüglich "Codeplex.BackupAddIn" kann ich nichts deaktiviertes finden

**Comment by myssv** [comment]
CalDavSyncronizer habe ich gefunden

![grafik](https://user-images.githubusercontent.com/65643813/171994995-ab6a2335-cfb8-4207-acb8-3d4d82105f37.png)

**Comment by myssv** [comment]
Es wurde nur eine outlook.exe gefunden

![grafik](https://user-images.githubusercontent.com/65643813/171995715-676f6468-f5d7-4b17-9687-6fbd10f39f36.png)

**Comment by myssv** [comment]
`Ich habe das Addin noch einmal deinstalliert und dann mit LOG neu installiert:

[install.log](https://github.com/HoffmannTom/outlookbackupaddin/files/8837514/install.log)
`

**Comment by HoffmannTom** [comment]
Hallo,
im Log sind soweit ich sehe keine Auffälligkeiten.
Wir können mal per Remote gucken, vielleicht sehen 4 Augen mehr als 2.
Dazu aber am besten über  die E-Mail-Adresse meines Profils Kontakt aufnehmen.

**Comment by HoffmannTom** [comment]
Ein Registry-Eintrag unter:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Microsoft\Office\Outlook\AddIns\Codeplex.BackupAddIn
verhinderte das Laden des Addins.
Das Löschen des Schlüssels brachte das Addin wieder zum Vorschein.
Der Zweig HKLM\SOFTWARE\Microsoft\Office\ClickToRun wird von Microsoft bei ClickToRun-Applikationen verwendet. Hierzu erfolgt ein virtualisierter Zugriff auf die Registry und diese werden auf oben genannten Schlüssel umgeleitet:
[https://docs.microsoft.com/de-de/archive/blogs/vsod/consdierations-while-readingwriting-registry-keys-under-hklm-from-office-addin-in-office-click-to-run#comment-5815](https://docs.microsoft.com/de-de/archive/blogs/vsod/consdierations-while-readingwriting-registry-keys-under-hklm-from-office-addin-in-office-click-to-run#comment-5815)
