### ISSUE TITLE
Backup every hour

### ISSUE THREAD

**Issue by screege** [HoffmannTom/outlookbackupaddin#75]
Hi I read you can make it backup every xx time via registry, read all readmes in the zip but cannot find the registry where to do it.

How can I accomplish that?

Regards

**Comment by screege** [comment]
Sorry found it at

HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings

Found IntervalHours and changed it to 1 supposing thats enough

Regards

**Comment by screege** [comment]
Changing the value to 1 and waiting over 1:30 hours with outlook open didn't autobackup anything, am I doing something wrong?

Regards

**Comment by HoffmannTom** [comment]
Hello,
the backup can only run when outlook is closed.
The add-in cannot do a backup while outlook is running because it locks the pst-files.
Therefore the time interval is checked when you close outlook.
Your settings mean: When I close outlook and the last backup is older than 1 hour, do backup again.

Greetings, Thomas

**Comment by screege** [comment]
Thank you, I closed outlook after more than an hour of the backup and still nothing, the backup has the same 7:26 am (currently 10:44) timestamp, I reopened outlook and again closed it and still no backup am I missing soemthing?

Regards

![image](https://user-images.githubusercontent.com/26051781/173102688-b655f02e-2a8a-4878-8bd4-3172444d3bcd.png)
![image](https://user-images.githubusercontent.com/26051781/173102748-6a5a4050-3127-4884-9241-cb736e4771f4.png)

**Comment by HoffmannTom** [comment]
Hm... when I look closer to your screenshot, you configured 1 day + 1 hour.
Maybe you can set interval to 0.
"LastRun" will be compared against the current time - Interval (days) - IntervalHours

**Comment by screege** [comment]
Maybe this optiones could be available in the GUI

Regards
