### ISSUE TITLE
Back up running slow

### ISSUE THREAD

**Issue by Dangitmanletmein** [HoffmannTom/outlookbackupaddin#77]
The outlook addin is working great for most of the users. There is one person who's back is running at 11mb when backing up. Everyone else is running at 80 to 90. Same building, same size pst going to the same network drive.

**Comment by HoffmannTom** [comment]
Hello,
the add-in is using windows default API to copy the files to the destination.
Maybe you can do a manual copy of the pst file and compare the throughput.
Greetings, Thomas

**Comment by HoffmannTom** [comment]
Hello,
do you have any feedback on this topic?
Otherwise, I would close this topic in the next days.

**Comment by Dangitmanletmein** [comment]
Thank you for your reply. You may close the ticket.

Thank you
William Lopez | Systems Engineer| SON Technology | www.Sontechnology.com<http://www.sontechnology.com/>
t. 407.936.2220 | ***@***.******@***.***>
