### ISSUE TITLE
Batch problem

### ISSUE THREAD

**Issue by Korn-ita** [HoffmannTom/outlookbackupaddin#78]
whent i try to insert a batch post backup (append_date.bat) i got an error, as reported down

Starting post-backup cmd: append_date.bat
""append_date.bat"" it is not recognized as an internal or external command

but if i run manually the batch the backup file i corretly renamed

**Comment by HoffmannTom** [comment]
Hello,
please try to include the path to the bat file.

**Comment by Korn-ita** [comment]
it worked, TNX!!!!
