### ISSUE TITLE
Turn PC off after backup

### ISSUE THREAD

**Issue by doundis** [HoffmannTom/outlookbackupaddin#79]
Hi,
many of our users have very large pst files, especially the graphics girls, so their back-up takes a lot of time.
Instead of having to wait for it to complete, so they can go home, they open the task Manager and end the process. Thus, no back-up!

It would help to have a checkbox at the back-up window, to turn the PC off after the back-up is complete.
Is it too crazy to ask for it?

**Comment by HoffmannTom** [comment]
Hello,
I added a checkbox and it will be available in the next release.
If you want to test it in advance, you can compile the current sources or drop a line (see profile information).

**Comment by HoffmannTom** [comment]
Hello,
the new version 1.11.0 contains the shutdown option.

**Comment by HoffmannTom** [comment]
👍🙂
