### ISSUE TITLE
Shutdown PC when Backup end

### ISSUE THREAD

**Issue by kanichrnd** [HoffmannTom/outlookbackupaddin#8]
is it possible to add checkbox which will shutdown PC after backup?

**Comment by HoffmannTom** [comment]
Hello,
you can choose the "post backup cmd" for this task.
Just write a small cmd or bat file with content "shutdown -s -f -t 0"
Save this file on your local hard disc.
Enter the path including filename in the field "post backup cmd" within the outlook addin configuration window.
After backup finishes, the batch file will be started and computer will shutdown.

Greetings,
Thomas

**Comment by kanichrnd** [comment]
Noted that, thank you
But I thought about checkbox which you can enable After backup starts.
I have about 10 PCs with ~30GB mailboxes on each
I scheduled monthly backup, but the user should be able to choose whether he wants to leave the computer turned on or not

**Comment by HoffmannTom** [comment]
Hello,
the task is not so easy because there might be other open programs with unsaved data.
You could either force a shutdown or use a normal shutdown which will wait till you handle this situation manually.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
another issue came into my mind. The window stays open if any errors occur.
The window will show information about the error (cause, message from subsystem, ...)
If it shuts down automatically there would be no information for the user whether the backup was ok.
This means possible errors (disk full, no write permission ...) wont be recognized by the user.
Therefore i wouldnt recommend this.

Greetings,
Thomas

**Comment by eL-Prova** [comment]
What about logging? You can atleast put a simple file or something to the desktop. Or why not sending an email and then shut down? ;-)

**Comment by HoffmannTom** [comment]
Hi,
messing up the desktop is not nice. I saw desktops where an additional icon would not attract any attention.
Email is not easy (configuring smtp, pop, imap, ssl, smtp after pop, start ssl protocol, mapi, active sync, ...
Implementing all possible configurations and combinations would require quite much configuration. And what if email sending is configured wrong?

One possibility would be to start a little program or batch file before calling the backupexecutor.exe
Replace the path and filename of backupexecutor.exe with your own program which handles the shutdown, then call backupexecutor and afterwards handle the shutdown (if selected).

I found a nice tutorial how it should work is https://www.sevenforums.com/tutorials/78083-batch-files-create-menu-execute-commands.html

Just ask whether shutdown should be activated, run backupexecutor and in the last step shutdown or just exit. Thus you can control the behaviour and also pipe the output of the program to desktop or somewhere else. Error handling is up to you and your responsibility. If you need further information about this method, just drop a line.

Regards,
Thomas

**Comment by eL-Prova** [comment]
Hi Thomas,

I just put some ideas where you can make it possible.
I think, when you are more experienced user, you should need to know how you can configure a smtp (thats only what you need). If you have trouble, it should not be your problem because you offer a possibility to let a email be sent after finish. I think, when you want something like this to offer. Keep it simple and instead of struggle with cmdlets you can let your user struggle with your UI :-)
If needed, I want to offer to help you.

**Comment by rhce143** [comment]
Does it take increemental backup of PST files? and he shedule backup task on which time how we can configure?

**Comment by HoffmannTom** [comment]
Hello rhce143,
please dont post off topic questions. This task is about shutting down after backup.
To answer shortly your question: no, it takes full backups of the pst-files.
