### ISSUE TITLE
Blocked by MS Defender ASR rules

### ISSUE THREAD

**Issue by JoergM-D** [HoffmannTom/outlookbackupaddin#80]
Hello,
since my complete reinstallation of my PC (Win 11 22H2 and Office 2019) Defender s blocking the Plugin. 
![image](https://user-images.githubusercontent.com/85316002/199795383-4bee5ff2-67c9-42ec-99a4-26f717d150dd.png)

Execption doesn't work...any idear, getting it running again?

**Comment by HoffmannTom** [comment]
Hello,
that's not the win10 defender. This is defender for endpoint, an enterprise solution.
I assume, that your computer is provisioned by your company which uses ASR rules in defender for endpoint (?)
In this case, only an IT guy can configure a whitelist in the ASR rule.
Greetings, Thomas

**Comment by JoergM-D** [comment]
Hello Tom,

 

thanks for your quick response. I’m using Windows 11 (22H2)and  I finnished the installation 4 days ago. Outlook is from Office 2019 Home and Business.

Before I started reinstalling everything, it was running…

 

Greetings Jörg

 

Von: HoffmannTom ***@***.***> 
Gesendet: Donnerstag, 3. November 2022 19:13
An: HoffmannTom/outlookbackupaddin ***@***.***>
Cc: JoergM-D ***@***.***>; Author ***@***.***>
Betreff: Re: [HoffmannTom/outlookbackupaddin] Blocked by MS Defender (Issue #80)

 

Hello,
that's not the win10 defender. This is defender for endpoint, an enterprise solution.
I assume, that your computer is provisioned by your company which uses ASR rules in defender for endpoint (?)
In this case, only an IT guy can configure a whitelist in the ASR rule.
Greetings, Thomas

**Comment by HoffmannTom** [comment]
The question is, if you have installed "Defender for endpoint" or if your Computer is connected to a company network?
ASR and how to configure it, is explained here (german version):
https://learn.microsoft.com/de-de/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide

**Comment by JoergM-D** [comment]
Nothing at all, it's a private Desktop-PC, Defender is the basic from Windows 11.I can't create/edit any policies-- Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 04.11.22, 12:38 schrieb HoffmannTom ***@***.***>:

   
  The question is, if you have installed "Defender for endpoint" or if your Computer is connected to a company network? ASR and how to configure it, is explained here (german version): https://learn.microsoft.com/de-de/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide

**Comment by HoffmannTom** [comment]
You can read about more on this pages:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#block-all-office-applications-from-creating-child-processes
It seems like Office is activating an ASR rule called "Block all Office applications from creating child processes"
If you dont have policies (home edition), you can use PowerShell to configure ASR rules:
https://4sysops.com/archives/configure-attack-surface-reduction-in-microsoft-defender-using-group-policy-or-powershell/

**Comment by JoergM-D** [comment]
H Tom,

 

I reinstalled my PC once again, now it’s running.

 

Cheers

Jörg

 

Von: HoffmannTom ***@***.***> 
Gesendet: Freitag, 4. November 2022 12:39
An: HoffmannTom/outlookbackupaddin ***@***.***>
Cc: JoergM-D ***@***.***>; Author ***@***.***>
Betreff: Re: [HoffmannTom/outlookbackupaddin] Blocked by MS Defender (Issue #80)

 

The question is, if you have installed "Defender for endpoint" or if your Computer is connected to a company network?
ASR and how to configure it, is explained here (german version):
https://learn.microsoft.com/de-de/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide
