### ISSUE TITLE
Not installing on Outlook 2013  with Windows 11

### ISSUE THREAD

**Issue by Philipdp13** [HoffmannTom/outlookbackupaddin#81]
I've had several goes at installing this addin on Outlook 2013 including running it it compatability mode with previous versions of windows.  It doesn't install but there are no error messages to indicate why and the install appears satisfactory.  I do have .NET 4.0 installed.

**Comment by HoffmannTom** [comment]
Hello,
can you try manual installation as described at https://github.com/HoffmannTom/outlookbackupaddin/wiki/Installation-instruction ?
Does the last command show any issues?

**Comment by Philipdp13** [comment]
Great - that worked a treat  - thank you

**Comment by HoffmannTom** [comment]
great :)
