### ISSUE TITLE
Inactive add inss

### ISSUE THREAD

**Issue by deepakdk2000** [HoffmannTom/outlookbackupaddin#82]
Unable to move the pulgin to active add ins. for Some user ( In 2007, 2013 and also for 2016 )
can someone help me out . With this

**Comment by deepakdk2000** [comment]
yea it is visible in pulgin but i tick the box and press ok it is not moving to active plugin.
i have Reinstalled both but its not working

**Comment by HoffmannTom** [comment]
Hello,
in 99% of the cases, there is a registry entry, preventing the plugin to load.
Please search the registry for "Codeplex.BackupAddIn" and check if the found entries are needed.

The keys
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
or
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
are needed for loading the plugin.

Other keys are not needed. To prevent future disabling, you can also add the Add-in to:
 HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\<version>\Outlook\Resiliency\DoNotDisableAddinList
see also: https://msdn.microsoft.com/en-en/library/office/mt651722.aspx?f=255&MSPPError=-2147217396 

Especially, entries in 
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\<version>\Outlook\Resiliency\DisabledItems
HKEY_CURRENT_USER\Software\Microsoft\Office\<version>\Outlook\Resiliency\CrashingAddinList
can prevent the plugin to load.

**Comment by HoffmannTom** [comment]
Hello, any new information about this topic?
If no feedback is provided, I will close this issue in one week.
