### ISSUE TITLE
No Outlook files shown

### ISSUE THREAD

**Issue by DaxAtDS9** [HoffmannTom/outlookbackupaddin#83]
There are no outlookfiles shown in the addin's setup...

**Comment by HoffmannTom** [comment]
Please check the wiki page 
[https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)](https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F) )

**Comment by DaxAtDS9** [comment]
Thank you! :-)
