### ISSUE TITLE
Add Date to Backup File Name

### ISSUE THREAD

**Issue by breeze74676** [HoffmannTom/outlookbackupaddin#84]
Hi!  Thanks for the great program.  After great effort I discovered you had 'scripts' one of which will add a date to the backup file name - I think.  Can't figure out what to do with this script...not sure how to 'run' it.  Can you please give me instructions?  I am a simple user and don't know technical stuff.  I saw the other two scrips which I would like to use as well.  Instructions for those would be helpful as well.  As I said...I know I am supposed to 'run' them...but I really don't know what that means.  Thank you!!!!

**Comment by HoffmannTom** [comment]
Hello,
this feature is intended for people who want to add features and know how to write scripts.
The script can be executed after the backup is finished.
The outlook dialog has a field "post-backup cmd". It is possible to add the path to a script file there.
The plugin will run the script after the backup.
Hope this helps. Greetings!

**Comment by HoffmannTom** [comment]
Hello,
are there any questions left?
I will close this issue in one week if there are no further questions.
