### ISSUE TITLE
Not all accounts are offered for backup

### ISSUE THREAD

**Issue by udoschm** [HoffmannTom/outlookbackupaddin#85]
I have 6 different mail accounts included in Outlook, but only one account is offered for backup. For each account, there is an .ost file.

![image](https://github.com/HoffmannTom/outlookbackupaddin/assets/102591157/520ea557-253c-49a4-ab01-689b6da19ff2)

**Comment by HoffmannTom** [comment]
Hi Udo,
please take a look at this wiki page: [https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F) ](https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F) )
It should answer your questions.
Greetings!

**Comment by udoschm** [comment]
Hi Tom,
thank you! It works 😄

**Comment by HoffmannTom** [comment]
Thank you👍
