### ISSUE TITLE
Cannot find new option for shutdown in version 1.11

### ISSUE THREAD

**Issue by dark0dev** [HoffmannTom/outlookbackupaddin#86]
It's not in the GUI, how to activate?
![gui](https://github.com/HoffmannTom/outlookbackupaddin/assets/21345126/09f4e8fe-5fb4-40f6-816b-142f1385161c)

**Comment by dark0dev** [comment]
ok, found it in the running process window,  so issue is kind of solved ;-)
![Unbenannt](https://github.com/HoffmannTom/outlookbackupaddin/assets/21345126/6ca5f8d0-d3c9-4700-9d2e-b3787a7e3736)

**Comment by HoffmannTom** [comment]
Yes... It is not a general setting but can be set on every backup individually.
Glad you found it :)
