### ISSUE TITLE
update previous version

### ISSUE THREAD

**Issue by heckt1ck** [HoffmannTom/outlookbackupaddin#89]
Hi!
First, great solution, thanks a lot!
Is there anything to take into consideration when updating a previously installed version?
What is the proper way to update?

Thanks again!
Best Regards
heckt1ck

**Comment by HoffmannTom** [comment]
Hi Tom!
The settings will be preserved.
You can just run the setup. If there are any problems, just uninstall the old version and install the new version.
Greetings!

**Comment by heckt1ck** [comment]
Thank you!
