### ISSUE TITLE
sync only changed parts

### ISSUE THREAD

**Issue by entchen66** [HoffmannTom/outlookbackupaddin#9]
hey,

isn't there a possibility via xcopy command to only copy changed parts of the outlook pst file? So when you do every day a backup, it souldn't copy the wohle pst, which is about 5 Gigs.

Chris

**Comment by HoffmannTom** [comment]
Hello,
xcopy will also perform a full copy. 
In windows networks, SMB or CIFS protocol is used. This protocol doesnt support incremental file copy with file compare.
A client which wants to transfer only changed parts would need to read the target file and compare it with local file. Reading 5 GBs via network and copy changed parts would take longer than copying 5 GBs without comparing/reading (except reading would be much faster).
Usually 1 GB network transfers around 100 MB per second (net transfer speed).
As HDD and SDD are much faster, the network is the limiting factor usually. 
Thus incremental copy within SMB networks would be slower than bulk copy.

Greetings,
Thomas

**Comment by entchen66** [comment]
okay, thanks for the answer ;)

**Comment by entchen66** [comment]
okay, thanks for the answer ;)
