### ISSUE TITLE
How to set additionnal scripts

### ISSUE THREAD

**Issue by MaTribu** [HoffmannTom/outlookbackupaddin#90]
Hi

I have tried to find any documentation related to how to set additionnal scripts provided with the main module.
Specifically this one "backup_additional_settings.bat"
How to configure the plugin in Outlook ?
Screen capture might help

**Comment by HoffmannTom** [comment]
Hello,
go to the settings page of the add-in and enter the full path in the field "post-backup cmd".
If there is a valid batch file then it will be executed after the backup is finished.
![image](https://github.com/HoffmannTom/outlookbackupaddin/assets/27145868/35cd4d62-e94d-4a5e-95a2-77168f4af885)

**Comment by HoffmannTom** [comment]
Hello,
is the provided information sufficient or do you need any further help?
