### ISSUE TITLE
Install of 1.11 failed - BACKUP not shown in ribbon

### ISSUE THREAD

**Issue by maxmaximax** [HoffmannTom/outlookbackupaddin#92]
Hello,

thank you for the great AddIn.

I'm running Win10 64bit and Outlook 2016 64bit.

Install of 1.9 and 1.10 was successful - the AddIn works like a charme.

Install of 1.11 failed - observations as follows:

BACKUP not shown in ribbon

BackupExecutor.exe /register
... detects my 64bit version as 32bit version (this is the same for 1.9 and 1.10)

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
... was NOT added to registry

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
... was successfully added to registry

Hope this can be fixed for 1.11.

Thank you,
maxmaximax

![Detected office 32 Bit](https://github.com/HoffmannTom/outlookbackupaddin/assets/82390306/6d9e2da4-1697-4594-acd3-4b55cfc3e391)

**Comment by HoffmannTom** [comment]
Hello Max,
the /register parameter seems to have issues when running on 64-bit OS.
For a quick fix, you could export the created registry branch, change the path via editor (delete Wow6432Node), and import the reg file again.
I will try to find a more reliable way to determine the bitness of the outlook.exe.

Thanks!
Thomas

**Comment by maxmaximax** [comment]
Hello Thomas,

this quick fix worked. Thank you!

Now, as the key is set correctly, can I just install any new version withouit worrying about the registry any longer?

Thanks,
Marcus

**Comment by HoffmannTom** [comment]
Hello Marcus,
there are two methods for registering the add-in. 
During installation, the correct registry key should have been created. If this doesn't happen, a logfile can be created via parameter. The installation procedure didn't change during the last releases, so I don't assume a general problem there.

The second method is the /register parameter, you were using. I will fix that problem.

If there is another issue during installation, we have to investigate that too. 

Greetings,
Thomas
