### ISSUE TITLE
Start  backup

### ISSUE THREAD

**Issue by fuel666** [HoffmannTom/outlookbackupaddin#94]
Hi,
Should the backup always start when Outlook is closed?

Because sometimes it starts suddenly when you close outlook.
Thank you

**Comment by HoffmannTom** [comment]
Hello,
the backup should only start if the last backup has reached the configured age.
When the time has elapsed, the next closing of outlook triggers the backup.

**Comment by fuel666** [comment]
Hello, 
so it is not possible for the backup to start without closing Outlook when the time has elasped,  Right?

**Comment by fuel666** [comment]
Hello,
Could it happen that on the day of the backup it starts closing Outlook
automatically?

Il ven 26 apr 2024, 15:12 HoffmannTom ***@***.***> ha scritto:

**Comment by HoffmannTom** [comment]
Hello,
there is currently no timer involved.
It might be annoying if Outlook is closed, during writing an email or working on something else.

**Comment by fuel666** [comment]
Certain.  Do you confirm that the add-in does not close Outlook to do the
backup but that you have to close Outlook manually?  Thank you

Il ven 26 apr 2024, 15:49 HoffmannTom ***@***.***> ha scritto:

**Comment by HoffmannTom** [comment]
Exactly... confirmed :)
The backup procedure is triggered on (manually) closing Outlook.

**Comment by fuel666** [comment]
Thank you

Best

Il ven 26 apr 2024, 16:33 HoffmannTom ***@***.***> ha scritto:
