### ISSUE TITLE
Where is the instalation File?

### ISSUE THREAD

**Issue by PEQSPC** [HoffmannTom/outlookbackupaddin#96]
I cant find the instalation file that which is mentioned in the readme OutlookBackupAddIn.msi

**Comment by HoffmannTom** [comment]
Hello! 
It should be within the zip asset.
-> Releases -> Assets -> zip File

**Comment by PEQSPC** [comment]
How i can run the backupAddin project i needs a password for the key.pfx

**Comment by HoffmannTom** [comment]
Do you want to install it or run it within visual studio for further development?
For installation you don't need a password, just run the msi file.
For development, you can create your own signing key.

**Comment by PEQSPC** [comment]
What is the backup countdown?

**Comment by PEQSPC** [comment]
Can you explain how to do this, I'm sorry I'm new to programming

**Comment by HoffmannTom** [comment]
When you close Outlook and the interval for backup has elapsed, the countdown gives you time to cancel the backup before it starts. This might be helpful if you can't wait for the backup to finish.

**Comment by PEQSPC** [comment]
Sometimes when doing the backup i get the error 32 ,i need to restart the pc and execute the .exe without opening the Outlook

**Comment by thomass4t** [comment]
Maybe you can add a full screenshot of the error window.
It might mean that the pst-file is locked by some other program and therefore can't be copied.
You can view any open handles with Process Explorer from Microsoft:
https://learn.microsoft.com/de-de/sysinternals/downloads/process-explorer  
Run as Admin --> Find --> Find Handle ...

**Comment by HoffmannTom** [comment]
closed because of no further feedback
